### ISSUE TITLE
Incorrect Minecraft Wiki link on documentation.

### ISSUE THREAD

**Issue by samuelh2005** [KyoriPowered/adventure#1013]
The Minecraft Wiki has moved to a new domain minecraft,wiki however some pages on the documentation site (like the [Books page](https://docs.advntr.dev/book.html)) still use the old Fandom site.

See https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom for more details.

**Comment by kezz** [comment]
Thanks! See also https://github.com/KyoriPowered/adventure-docs/pull/156

**Comment by samuelh2005** [comment]
Closing as the PR is merged.
