### ISSUE TITLE
sendMessage bug

### ISSUE THREAD

**Issue by deestt** [KyoriPowered/adventure#1019]
Hi
`default void sendMessage(final @NotNull Component message, final ChatType.@NotNull Bound boundChatType) {
        this.sendMessage(message, MessageType.CHAT);
    }

    @ForwardingAudienceOverrideNotRequired
    default void sendMessage(final @NotNull ComponentLike message, final ChatType.@NotNull Bound boundChatType) {
        this.sendMessage(message.asComponent(), boundChatType);
    }`
Parameter boundChatType isn't used

**Comment by Machine-Maker** [comment]
I believe this is intentional. That method is for being overridden by implementations of Audience and they do use the boundChatType
