### ISSUE TITLE
java.lang.IncompatibleClassChangeError when attempting to use player.sendMessage()

### ISSUE THREAD

**Issue by Wolvinny** [KyoriPowered/adventure#1028]
I've freshly installed this, and i'm trying with the most basic code in the docs
Sender is a Player instance.

```java
  MiniMessage mm = MiniMessage.miniMessage();
  Component parse = mm.deserialize("<green>test</green>");
                    Audience au = (Audience) sender;
                    au.sendMessage(parse);
```
The docs dont really explain what Audience should be, the example just shows `Audience =...`.
Tried without casting, that threw a noSuchMethodError.
This code produces the following error

`Caused by: java.lang.IncompatibleClassChangeError: Class org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer does not implement the requested interface net.kyori.adventure.audience.Audience`

Dependencies: 

```xml
      <dependency>
          <groupId>net.kyori</groupId>
          <artifactId>adventure-text-minimessage</artifactId>
          <version>4.14.0</version>
      </dependency>
      <dependency>
          <groupId>net.kyori</groupId>
          <artifactId>text-adapter-bukkit</artifactId>
          <version>3.0.6</version>
          <scope>compile</scope>
      </dependency>
```

Server is running craftbukkit, 1.20.4, plain vanilla with no other plugins.
I might be overlooking something but i've been stuck at this for a while now

**Comment by kezz** [comment]
You cannot just cast a player to an audience. You need to properly use an in-date and supported version of [adventure-platform-bukkit](https://docs.advntr.dev/platform/bukkit.html). If you need more assistance I'd recommend jumping into our [Discord](https://discord.gg/MMfhJ8F) or using our [Discussions](https://github.com/KyoriPowered/adventure/discussions) page.

**Comment by Wolvinny** [comment]
i must've skipped past that somehow. works now! thanks!
