### ISSUE TITLE
Add a name/key to `TranslationArgument`

### ISSUE THREAD

**Issue by kezz** [KyoriPowered/adventure#1037]
Whilst unused in vanilla, it would be a pretty handy feature to have. For example, #972 could have named arguments based on the names of a `TranslationArgument`.

**Comment by zml2008** [comment]
I'm not super sure how I feel about this, since it'd go ahead of what the vanilla format can represent at this point in time -- virtual components are imo still the way forward for richer translations.

**Comment by kezz** [comment]
> virtual components are imo still the way forward

I was actually playing about with virtual components on top of #972 and yeah, it does what we'd need for this anyway!
