### ISSUE TITLE
`fastjson2` component serializer

### ISSUE THREAD

**Issue by DxrkCxt** [KyoriPowered/adventure#1039]
Is your feature request related to a problem? Please describe.
No, this is related to the idea of improving performance in json moments.
Describe the solution you'd like
https://github.com/alibaba/fastjson2 - This library is actively supported and fully stable, but its performance is better than gson, you can see by benchmarks
https://github.com/fabienrenaud/java-json-benchmark - benchmark tests (gson vs fastjson2)
Describe alternatives you've considered to solve your solution without
us adding this as a feature?

**Comment by kezz** [comment]
You are welcome to make your own library that implements `JsonComponentSerializer` and if you do we'd be happy to include it in our [community libraries page ](https://docs.advntr.dev/community-libraries.html). However, the team is not going to be working on or maintaining such a library.
