### ISSUE TITLE
`ListBinaryTag` is weakly immutable

### ISSUE THREAD

**Issue by mworzala** [KyoriPowered/adventure#1070]
List stores an immutable view of the input lists, it should do a defensive copy (eg `List.copyOf`).

```java
var entries = new ArrayList<BinaryTag>();
entries.add(StringBinaryTag.stringBinaryTag("abc"));
entries.add(StringBinaryTag.stringBinaryTag("def"));
var tag = ListBinaryTag.listBinaryTag(BinaryTagTypes.STRING, entries);
entries.clear();
assert tag.size() == 2; // fails
```

**Comment by RealBauHD** [comment]
You are right, normally new lists and maps are created for the wrapped immutables, because JEP 269 was introduced in Java 9. I'll take a look at the places where it was forgotten.

**Comment by RealBauHD** [comment]
It seems that only `ListBinaryTag#listBinaryTag` uses no copy, have you tested it with the `CompoundBinaryTag`?

**Comment by mworzala** [comment]
Yep you're right sorry, compound wraps it correctly I misread.
