### ISSUE TITLE
[Bug] LegacyComponentSerializer removing text before char when a single color code is used

### ISSUE THREAD

**Issue by STG-Allen** [KyoriPowered/adventure#108]
When using `LegacyComponentSerializer.legacy('&').deserialize(message)`, the deserializer will remove any text before the color code if there is only one color code present in the string.

Expected Behavior: 

In text 3.x, the deserializer would ignore all text until it reached a color code and would then deserialize it from there leaving the text before it untouched.

Steps to reproduce: 

1. Create a LegacyComponentSerializer that deserializes text for ampersand's
2. Run the following text through the serializer: 
```
One: Test &aString
Two: &bTest &aString
```
Note, when using text 3.x, the deserializer left the word `Test` in the first string white, and converted `String` to green.

Example: 

https://cdn.discordapp.com/attachments/478128992344473600/734535624706752612/unknown.png

**Comment by astei** [comment]
`adventure`'s legacy serializer translates that string into this code equivalent:
```
    final TextComponent comp = TextComponent.builder("One: Test ")
      .append(TextComponent.of("String\nTwo: ", NamedTextColor.GREEN))
      .append(TextComponent.of("Test ", NamedTextColor.AQUA))
      .append(TextComponent.of("String", NamedTextColor.GREEN))
      .build();
```
This appears to be _literally_ correct. Are we looking at a gson serializer bug or a client issue? What Minecraft version did you use?

**Comment by zml2008** [comment]
hm, I've been able to reproduce this issue on latest master with the following test case:

```java
  @Test
  void testBeginningTextUnformatted() {
    final String input = "Test &cString";
    final TextComponent expected = TextComponent.builder("Test ")
      .append(TextComponent.of("String", NamedTextColor.RED))
      .build();

    assertEquals(expected, LegacyComponentSerializer.legacy(LegacyComponentSerializer.AMPERSAND_CHAR).deserialize(input));

  }
```

**Comment by STG-Allen** [comment]
I believe my formatting was misleading as I meant to run each one seperatly. I am using MC Version 1.12.2.

**Comment by astei** [comment]
I suspect #82 may have introduced this bug. I have a fix to be pushed up soon.
