### ISSUE TITLE
Line break turns into LF character

### ISSUE THREAD

**Issue by Lukadcf** [KyoriPowered/adventure#1100]
When I use < br>, < newline>, .appendNewline() or \n in lore components it doesn't go to the next line, instead it shows the raw character.

Code:
```
 String string = "<newline><gold>Ability: Pocket Spells<br><gray>ᴜѕᴇ ʏᴏᴜʀ <#665de3><i>ᴄᴏɴꜰɪɢᴜʀᴇᴅ</i></#665de3> ѕᴘᴇʟʟѕ!";
 MiniMessage.miniMessage().deserialize(string).decorationIfAbsent(TextDecoration.ITALIC, TextDecoration.State.FALSE);
```

Result:
![image](https://github.com/user-attachments/assets/3ee933c9-f55f-44ab-bebf-3a529ac1fd8b)

**Comment by mbax** [comment]
Lore is a list of components, not a single component with linebreak characters. Create your lore components line at a time.

**Comment by Lukadcf** [comment]
> Lore is a list of components, not a single component with linebreak characters. Create your lore components line at a time.

Ah, thank you.
I created this simple method to split the lines if someone gets the same issue

```
public List<Component> stringToComponentList(String string) {
        List<Component> lore = new ArrayList<>();
        
        MiniMessage mm = MiniMessage.miniMessage();
        String[] strings = string.split("<br>");
        for (String line : strings) {
            lore.add(mm.deserialize(line).decorationIfAbsent(TextDecoration.ITALIC, TextDecoration.State.FALSE));
        }
        return lore;
    }
```
