### ISSUE TITLE
Legacy decode does not consider options of builder...

### ISSUE THREAD

**Issue by nicolube** [KyoriPowered/adventure#1116]
Hello,

I have build a serializes looking like this.

```java
                LegacyComponentSerializer.builder()
                        .character(LegacyComponentSerializer.AMPERSAND_CHAR)
                        .formats(LEGACY_COLOR)
                        .build());
```

I wanted to use it to translate just ChatColors, but it still docdes stuff like this:
`&x&f&f&f&f&f&eYour Text`

Which I think should only work when `useUnusualXRepeatedCharacterHexFormat()` was used in the builder.

**Comment by zml2008** [comment]
What is the use case for this? Changing these defaults will likely break plugins currently in use.

**Comment by nicolube** [comment]
@zml2008 As mentioned above, we use it for converting chat colors.

If a user types `&x&f&f&f&f&f&eYour Text`, we get something like this.
![Image](https://github.com/user-attachments/assets/a41fb8e6-143b-4167-b583-14c832cc9713)

But it is disabled by default, the issue is just that is not checked on deserialize , only in serialize.
So we cannot disable `useUnusualXRepeatedCharacterHexFormat()` is we want to.

**Comment by nicolube** [comment]
Also the same issue exists with Kyori chat colors `&#FF0000Some text`, which needs also needs be enabled via `hexColors()` in builder to work.

But currently it also works without enabling on deserialize.

**Comment by zml2008** [comment]
Why are you checking the style in the serializer, which is specific to the legacy format? You could just as easily strip formatting from the resulting component after deserializing (which would apply to any formatting option supported in the legacy serializer, not just the RGB colours).

As-is, it sounds like you're asking for an incomplete solution that changes behaviour. If more flexibility were added, I think it'd make sense to be done similarly to the JSONOptions flags, where the default options are as-is, but individual options can be toggled to match specific game versions.

**Comment by nicolube** [comment]
Ahh ok, I see always de-serializer is a feature of this.

Would it be fine to add something to the builder one could disable it?

`Builder#format` has a different behavior as `Builder#hexColor` and `Builder#useUnusualXRepeatedCharacterHexFormat`

`Builder#format` allows u to change the behavior of both serialization and deserialization

 `Builder#hexColor` and `Builder#useUnusualXRepeatedCharacterHexFormat` only lets one change the serialization behavior...

Is that wanted?

**Comment by zml2008** [comment]
No. Please read what I said about the system that the gson serializer uses.

**Comment by nicolube** [comment]
Yes I have seen that.

I just got a bit confused because `Builder#format` changes both and the other 2 does not...

Should in this case [`LegacyComponentSerializerImpl#decodeTextFormat`](https://github.com/KyoriPowered/adventure/blob/main/4/text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerImpl.java#L139) not rater use `CharacterAndFormatImpl.Defaults.DEFAULTS` instead of `this.formats` so that it also only apply to serialize?

**Comment by zml2008** [comment]
So hot take after letting this sit for a bit, I don't think it's worthwhile doing some sort of colour-by-colour restrictions on the legacy serializer -- it's only around to work with existing old data, so any extra maintenance burden for those sorts of features is hard to justify.
