### ISSUE TITLE
Using \n (or <br> in mini) in multiline hover text breaks color on legacy

### ISSUE THREAD

**Issue by kangarko** [KyoriPowered/adventure#1132]
Inconsistent behavior in use of \n or `<br>` to render hover text multiline. On legacy, this breaks the line color. MiniMessage parsing is also affected.

 Is this unsupported or is there a better alternative?

**Expected (works on 1.21.3):**
![a](https://i.imgur.com/tFlZANd.png)

**Got (tested on 1.8.8):**
![b](https://i.imgur.com/8xv1eH9.png)

(Please note the code below does not contain color formatting of the chat message but only in hover, which is where the bug occurs)

**Code to reproduce:**

```java
final Component miniComponent = MiniMessage.miniMessage().deserialize("<red>[Mini] First line\nSecond line");

audience.sendMessage(Component.text("[Mini] Test hover").hoverEvent(HoverEvent.showText(miniComponent)));
audience.sendMessage(Component.text("[Adventure] Test hover").hoverEvent(HoverEvent.showText(Component.text("[Native] First line\nSecond line").color(NamedTextColor.RED))));
```

Update: Turns out by using appendNewline() the first color is retained. However I cannot achieve this using minimessage, is there a way to fix it there for better user experience?

**This code works consistently on all platforms:**

```java
audience.sendMessage(Component.text("[Adventure] Test hover").hoverEvent(HoverEvent.showText(Component.text("[Native] First line").color(NamedTextColor.RED).appendNewline().append(Component.text("Second line")))));
```

Thanks
Matej

**Comment by electronicboy** [comment]
using legacy colors defeats the entire point of migrating over to components, and is 100% unsupported behavior. 

MM doesn't have a means to cause appending a new newline component as a child, which is odd and creates a case which breaks a > b > a; this is an issue because it means that we rely on the behavior of \n in the client which has been oddly inconsistent and breaky over the years

**Comment by kangarko** [comment]
> using legacy colors defeats the entire point of migrating over to components, and is 100% unsupported behavior.
The issue happens regardless if §c was used or not. In my opinion, the legacy formatting was far superior for simple scenarios, as it's shorter, easier to remember and faster.

> MM doesn't have a means to cause appending a new newline component as a child, which is odd and creates a case which breaks a > b > a; this is an issue because it means that we rely on the behavior of \n in the client which has been oddly inconsistent and breaky over the years

I managed to fix it, please consider redesigning the relevant part of minimessage parser to accommodate this logic, that would be amazing:

![a](https://i.imgur.com/5LT583p.png)

Code:

```java
private static Component fixMultilineHoverText(Component adventure) {
	if (adventure.hoverEvent() != null) {
		final HoverEvent<?> hover = adventure.hoverEvent();

		if (hover.action() == Action.SHOW_TEXT) {
			final Component oldHover = (Component) hover.value();
			final String oldMini = MiniMessage.miniMessage().serialize(oldHover);

			if (oldMini.contains("\n")) {
				final String[] oldLines = oldMini.split("\n");
				Style lastStyle = null;

				for (int i = 0; i < oldLines.length; i++) {
					final String line = oldLines[i];

					if (lastStyle != null) {

						// Append decorations
						for (final Map.Entry<TextDecoration, State> entry : lastStyle.decorations().entrySet())
							if (entry.getValue() == State.TRUE)
								oldLines[i] = "<" + entry.getKey().name() + ">" + line;

						// Append color
						oldLines[i] = "<" + darkenOneShade(lastStyle.color()).asHexString() + ">" + line;
					}

					lastStyle = LastMessageStyleParser.parseStyle(line);
				}

				final String newMiniHover = String.join("\n", oldLines);

				adventure = adventure.hoverEvent(HoverEvent.showText(MiniMessage.miniMessage().deserialize(newMiniHover)));
			}
		}
	}

	if (!adventure.children().isEmpty()) {
		final List<Component> newChildren = new ArrayList<>();

		for (final Component child : adventure.children())
			newChildren.add(fixMultilineHoverText(child));

		adventure = adventure.children(newChildren);
	}

	return adventure;
}

private static TextColor darkenOneShade(TextColor color) {
	final String hex = color.asHexString();

	final int r = Math.max(0, Integer.parseInt(hex.substring(1, 3), 16) - 1);
	final int g = Integer.parseInt(hex.substring(3, 5), 16);
	final int b = Integer.parseInt(hex.substring(5, 7), 16);

	return TextColor.color(r, g, b);
}
```

The source of LastMessageStyleParser is in my library [Foundation's SimpleComponent](https://github.com/kangarko/Foundation/blob/v7/foundation-core/src/main/java/org/mineacademy/fo/model/SimpleComponent.java) class.

**Explanation:**

I implemented a method to first loop through all components, then find all hover components, parse them back to minimessage, check if they contain a new line, then split the lines and append the last color/style from the previous line onto the new line.

One small issue was that minimessage omits the style if it's the same as the previous, so we had to shift the shade one bit (which is invisible on legacy due to downsampling).

**How to use & demo:**

I will ship this into our [Foundation 7 library](https://github.com/kangarko/Foundation/blob/v7/foundation-core/src/main/java/org/mineacademy/fo/model/SimpleComponent.java) tonight or tomorrow. Anyone reading and finding this useful can use it. Here is an example format (please note we support legacy tags as well as minimessage tags):

````java
this.audience.sendMessage(SimpleComponent.fromMini("<hover:show_text:'<red>first &e&lline\nsecond line'><gradient:red:gold>Click here to learn more</gradient></hover>"));
````

**Comment by kezz** [comment]
The issue is not with MiniMessage or adventure, it is with you mixing legacy and normal formatting. There are no issues with newlines in hover message components created using MiniMessage.

If you need help migrating away from legacy, we're happy to answer any questions in GitHub Discussions or our Discord, but mixing and matching legacy and Components are not supported.

**Comment by kangarko** [comment]
@kezz Unfortunately your statement is invalid, as I said above I get the same results even when only using minimessage format with modern tags.

**Comment by kezz** [comment]
Please provide an MWE/MRE as I cannot reproduce this.

**Comment by kangarko** [comment]
Keep in mind I am talking about 1.8.8. The color is properly retained on the second line on 1.21.1.

**Code:**

````java
final Component miniComponent = MiniMessage.miniMessage().deserialize("<red>[Mini] First line\nSecond line");

audience.sendMessage(Component.text("[Mini] Test hover").hoverEvent(HoverEvent.showText(miniComponent)));
audience.sendMessage(Component.text("[Adventure] Test hover").hoverEvent(HoverEvent.showText(Component.text("[Native] First line\nSecond line").color(NamedTextColor.RED))));
````

**Result:**

![a](https://i.imgur.com/v8osb02.png)

I think @electronicboy correctly explained why it does not work unless changes are made on your end.

**Comment by kangarko** [comment]
I think the issue is simple, the old client resets the formatting on every new line, so the solution is to reapply the last line's formatting. I designed a workaround above but I am unsure about the design strategy of it for Adventure.

**Comment by zml2008** [comment]
This one is the duplicate of #50

**Comment by kangarko** [comment]
@kezz so a fix is still not planned? Thanks.

**Comment by zml2008** [comment]
PRs are welcome, this is not a priority for the team though because it doesn't affect newer game versions.

**Comment by kangarko** [comment]
Gotcha. Same here, as a plugin dev supporting a decade of versions is quite tiresome so I dropped the internal fix for now and legacy users will just need to append colors manually.
