### ISSUE TITLE
MiniMessage merges two colors, breaking messages with placeholders

### ISSUE THREAD

**Issue by kangarko** [KyoriPowered/adventure#1139]
How can I disable MiniMessage automatically removing the second `<gray>` from `<gray>Hello {player} <gray>this is a test!`

We need to disable this feature because in case the player variable itself has a color, we need to keep the second `<gray>` tag to reset it back.

In this scenario, using MiniMessage tags is not an option. 

Thanks,
Matej

**Comment by kezz** [comment]
Disabling the post-processor compactor would likely fix this, but the supported solution would be to use tags.

**Comment by kangarko** [comment]
Thanks, I'm unfamiliar with these terms, mind giving me direction in code how to do it?

**Comment by KingOfSquares** [comment]
When building your MiniMessage instance you can disable the post-processor with 
https://jd.advntr.dev/text-minimessage/4.17.0/net/kyori/adventure/text/minimessage/MiniMessage.Builder.html#postProcessor(java.util.function.UnaryOperator) and just a empty function.

MiniMessage placeholder tags are documented here: https://docs.advntr.dev/minimessage/dynamic-replacements.html

**Comment by kangarko** [comment]
@KingOfSquares thanks, got it! The MiniMessage works now, however the issue persist when translating back to legacy.

**Code:**

```java
final String message = "<gray>Hello {player} <gray>this is a test!";
final Component mini = MiniMessage
		.builder()
		.tags(TagResolver.standard())
		.strict(false)
		.preProcessor(UnaryOperator.identity())
		.postProcessor(UnaryOperator.identity())
		.debug(null)
		.build()
		.deserialize(message);

final String json = GsonComponentSerializer.gson().serialize(mini);
final String legacy = LegacyComponentSerializer.legacySection().serialize(mini);

System.out.println("Json: " + json);
System.out.println("Legacy: " + legacy);
```

**Output:**

```
Json: {"extra":[{"color":"gray","extra":["Hello {player} ",{"color":"gray","extra":["this is a test!"],"text":""}],"text":""}],"text":""}
Legacy: §7Hello {player} this is a test!
```

The json is now properly not flattened but the legacy is. I tried to follow your approach with the builder on the legacy serializer to no avail, do you know of any solutions or is this a bug?

Many thanks,
Matej

**Comment by KingOfSquares** [comment]
@kangarko I believe this is the Legacy serializer not applying the format since it does not "change".
I think this is the relevant code: https://github.com/KyoriPowered/adventure/blob/18a9e9fcb007b38f1ce256160d1f72d3d3e0af87/text-serializer-legacy/src/main/java/net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializerImpl.java#L400-L406

Is there no way you can build the component after the variable is known?

**Comment by kangarko** [comment]
Thanks for the clarification!

Well I could, but I cache the Component for performance reasons when the plugin starts. The idea is to use Component#replaceText("{player}", X).

Replacing the entire plugin from {} to <> tags would not be desirable. 

I tried copying said class and removing this toggle, but the results were the same. If you are knowledgeable in Adventure and have a minute I'd really appreciate if you could add a toggle for this for that builder.

Matej

**Comment by MiniDigger** [comment]
> Well I could, but I cache the Component for performance from my language file upon boot. The idea is to use Componet#replaceText("{player}", X).

are you positive that that is actually significantly faster than using placeholders? given the speed of minimessage, I kinda doubt that.

**Comment by KingOfSquares** [comment]
If you're using replaceText you probably wont notice much performance difference, the replace method creates new Components and the MiniMessage parser is very fast.

I think adding a toggle to enable behaviour like this in the legacy serializer is unfit for Adventure, but you're free to copy the code and add it yourself. Just remember to copy license text like the MIT license describes :)

**Comment by kangarko** [comment]
> > Well I could, but I cache the Component for performance from my language file upon boot. The idea is to use Componet#replaceText("{player}", X).
> 
> are you positive that that is actually significantly faster than using placeholders? given the speed of minimessage, I kinda doubt that.

Good point. I'll measure it and make adjustments. Thanks!



> If you're using replaceText you probably wont notice much performance difference, the replace method creates new Components and the MiniMessage parser is very fast.
> 
> I think adding a toggle to enable behaviour like this in the legacy serializer is unfit for Adventure, but you're free to copy the code and add it yourself. Just remember to copy license text like the MIT license describes :)

Thanks!
