### ISSUE TITLE
"key" tags are not self closing

### ISSUE THREAD

**Issue by NonSwag** [KyoriPowered/adventure#1140]
When using a strinct MiniMessage parser `key` tags have to be manually closed
I was wondering if this is intended behavior or just an oversight

![Image](https://github.com/user-attachments/assets/51512613-9904-49aa-b88e-0ded81c18aaf)

**Comment by zml2008** [comment]
This is intended, key tags can have children. Use `<key:up/>` with the closing slash as shorthand.
