### ISSUE TITLE
Click event broken on Paper 1.21.4

### ISSUE THREAD

**Issue by kangarko** [KyoriPowered/adventure#1141]
The following code works on 1.8.8 using BukkitAudiences but the clickevent does not work at all in 1.21.1 and 1.21.4 (I have not tested versions between those).

**Code:**

```java
String mini = "<hover:show_text:'Click to run'><click:run_command:'/say hey'>[click me]</click></hover>";
Component component = MiniMessage.miniMessage().deserialize(mini);

System.out.println("Json: " + GsonComponentSerializer.gson().serialize(component));

this.getPlayer().sendMessage(component);
```

**Edit**: Even using click event nativelly does not work:

```java
Component.text("[click me]").hoverEvent(HoverEvent.showText(Component.text("Click to run"))).clickEvent(ClickEvent.runCommand("/say hey"))
```

**Version:**

This server is running Paper version 1.21.4-14-master@b746d9d (2024-12-11T21:22:39Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

**Plugins**

Just my testing plugin with the above snippet.

**Comment by kangarko** [comment]
Upon further investigating even doing "/tellraw kangarko {"clickEvent":{"action":"run_command","value":"/say hey"},"hoverEvent":{"action":"show_text","contents":"Click to run"},"text":"[click me]"}" does make the clicking work. I am doing something wrong, is my server misconfigured?

**Comment by powercasgamer** [comment]
This is due to signed commands since 1.19. Not a Paper or Adventure issue

**Comment by kangarko** [comment]
Okay so only way to "fix" this is to cancel the chat event and send the message as system chat?

**Comment by zml2008** [comment]
You'd have to make your own command - /say doesn't work because it has signed arguments

**Comment by kangarko** [comment]
@zml2008 is there a page listing all commands that contain signed arguments (MC wiki doesn't say anything about this)? /say, /me, /tell... anything else? I will alert my users of this and prepare alternative commands. 

Thank you for the swift response!

**Comment by MiniDigger** [comment]
![Image](https://github.com/user-attachments/assets/294d3733-1395-4cd0-b5c5-b280d4ba9343)

**Comment by kangarko** [comment]
Thank you!
