### ISSUE TITLE
Rename Component -> Text & TextComponent -> LiteralText like in Sponge API

### ISSUE THREAD

**Issue by XjCyan1de** [KyoriPowered/adventure#142]

**Comment by kashike** [comment]
This is not something that is going to happen, sorry.

**Comment by XjCyan1de** [comment]
I would like to hear an opinion on why the name Component is more suitable for the definition, although even the package name says that it is text

**Comment by kashike** [comment]
A few reasons:
- this has been the name of the class since [2017 when the first commit was pushe](https://github.com/KyoriPowered/adventure/commit/4cd69ae96cb4140e432c2b260b806c8db12b9c83)
- `Component` is the name Mojang Studios has given this format - - `argument.component.invalid` translation key with value `Invalid chat component: %s` in American English

**Comment by XjCyan1de** [comment]
many class names from Mojang don't always fit the right context. The same worlds that are named "Levels", chunks that are named as "Columns" (although in some places they are still called chunks). It is not always rational to focus on the names given by the developers of minecraft. In the Sponge API, " text components "are named exactly as"Text". And the name "Component" is too abstract, even in official deobfuscation mappings from Mojang, these classes are named as ' net. minecraft.network.chat.TextComponent`

**Comment by kashike** [comment]
This is not something that we are going to be changing any time soon, for the reasons I have already specified.


> In the Sponge API, " text components "are named exactly as"Text". And the name "Component" is too abstract, 

This is not the Sponge API.

> even in official deobfuscation mappings from Mojang, these classes are named as `net.minecraft.network.chat.TextComponent`

Incorrect - `net.minecraft.network.chat.Component` matches with our `Component`, and so on.
