### ISSUE TITLE
Allow Audiences to be modified after creation to filter them by either a predicate or another audience.

### ISSUE THREAD

**Issue by Narimm** [KyoriPowered/adventure#154]
The concept here is to minimize the need to for loop through targets to send a message to a subset of the server audience, where that subset is not provided by the existing methods in audienceProvider eg. `all()`, `world()`,`server()`,`permission(String)` etc

It would be ideal to take the provided audience and filter it either by a predicate, which as discussed might need to be platform-specific, or by another audience set.
`audienceProvider.permission("some.permission", somePredicate)`

or in the case of another audience set.

`AudienceProvide.all().exclude(AudienceProvider.world("someworld").sendmessage()`

Consideration would need to made, as to whether the implementation is better optimized than example like the for loop below.

This would avoid code like 
```java 
//from a bukkit plugin 
for(Permissible perm : targets)
        {
            if(perm == except)
                continue;
            
            if(perm instanceof CommandSender && (permission == null || perm.hasPermission(permission)) && (checker == null || checker.isValid((CommandSender)perm)))
                audienceProvider.audience((CommandSender) perm).sendMessage(message);
        }
```

**Comment by kezz** [comment]
Closing this based on the merge of #365.
