### ISSUE TITLE
Add Audience#filter method

### ISSUE THREAD

**Issue by astei** [KyoriPowered/adventure#155]
This method would allow a user of the Adventure API to easily synthesize audiences that meet some arbitrary condition, i.e.

```java
audience.filter(this::canSeeAnnouncements).sendMessage(announcement);
```

This method has many uses that are far too many to enumerate here.

**Comment by Narimm** [comment]
is this not effectively a duplicate of #154

**Comment by astei** [comment]
I talked with kashike before filing this issue, and he said your issue is better placed in adventure-platform, not adventure itself.

**Comment by Narimm** [comment]
Yeah we discussed the differences as well - I just wondered with mine is just not an extension really of yours
