### ISSUE TITLE
Improve ability to statically import factory methods

### ISSUE THREAD

**Issue by kashike** [KyoriPowered/adventure#159]
Stage 1: add new methods:
- [ ] `Book.book` (like `builder` and `of`)
- [ ] `Key.key` (like `builder` and `of`)
- [ ] `Sound.sound` (like `builder` and `of`)
- [ ] `ClickEvent.clickEvent` (like `of`)
- [ ] `HoverEvent.hoverEvent` (like `of`)
- [ ] `Style.style` (like `builder` and `of`)
- [ ] `TextColor.color` (like `of`)
- [ ] `Title.title` (like `builder` and `of`)

and the same with all the `Component` types

Stage 2: remove existing methods:
- [ ] `of` methods

**Comment by jamierocks** [comment]
This improves the readability of some code at the cost of other code. A better solution could have been retaining the existing `#of()` methods, with a new `StaticHelper` class with things like:
```java
public static Book book(...) { return Book.of(...); }
public static Key key(...) { return Key.of(...); }
```

**Comment by kashike** [comment]
> at the cost of other code

Such as?

**Comment by jamierocks** [comment]
Perhaps you may disagree with me, but I think that `Book.book(...)` looks terrible.

**Comment by kashike** [comment]
I would not say that it looks terrible. If anything, it is a bit of repetition, sure.

We used to have something like `StaticHelper` in the past and it was ignored.
