### ISSUE TITLE
Not resetting text after a bold element when using LegacyComponentSerializer

### ISSUE THREAD

**Issue by rtm516** [KyoriPowered/adventure#206]
When converting a parsed JSON component to legacy formatting, the bold flag doesn't get reset properly. Therefore causing them to go beyond where they are meant to.

This is similar to https://github.com/KyoriPowered/adventure/issues/195 which was fixed with https://github.com/KyoriPowered/adventure/commit/059904899f74134139b62c47e1fcdf9306df6c29 but it still happens with this json and the bold flag

Version: 4.1.1 (adventure-api), 4d8a67d798 (adventure-text-serializer-gson), adventure-text-serializer-legacy (0599048)
Note: I have tested this with the latest commit in the repo with no change

Conversion code:
https://github.com/GeyserMC/Geyser/blob/master/connector/src/main/java/org/geysermc/connector/network/translators/chat/MessageTranslator.java#L80-L88
```java
public static String convertMessage(String message, String locale) {
        Component component = GsonComponentSerializer.gson().deserialize(message);

        // Get a Locale from the given locale string
        Locale localeCode = Locale.forLanguageTag(locale.replace('_', '-'));
        component = RENDERER.render(component, localeCode);

        return LegacyComponentSerializer.legacySection().serialize(component);
}
```

JSON input:
```json
{"text":"","extra":[{"text":"","extra":[{"text":"[","color":"gray"},{"text":"H","color":"yellow"},{"text":"]","color":"gray"},{"text":" ","color":"white"},{"text":"GUEST","color":"#b7b7b7","bold":true}]},{"text":"","extra":[{"text":" ","bold":true},{"text":"»","color":"blue"},{"text":" ","color":"gray"}]},{"text":"","extra":[{"text":"rtm516","color":"white"},{"text":": ","color":"gray"},{"text":"","color":"white"}]},{"text":"","extra":[{"text":"This is an amazing bedrock test message","color":"white"}]}]}
```

Legacy output:
```
§7[§eH§7]§f §7§lGUEST§r§l §9»§7 §frtm516§7: §fThis is an amazing bedrock test message
```

Json display: (Java, before conversion)
![image](https://user-images.githubusercontent.com/5401186/99444849-a89edb80-2914-11eb-8418-a45752a59475.png)

Legacy display: (Bedrock, after conversion)
![image](https://user-images.githubusercontent.com/5401186/99444874-b0f71680-2914-11eb-9d7b-e26412bfdec5.png)

**Comment by Phoenix616** [comment]
That is indeed the correct behaviour (for Java). A legacy color character after a formatting character will reset the formatting therefore a reset character is not necessary there. This seems to be a different behaviour between Bedrock and Java.

**Comment by rtm516** [comment]
Ah, thanks for pointing this out. I found a solution to make it more act like Java formatting when sent to bedrock.
```java
legacy = legacy.replaceAll("\u00a7([0-9a-f])", "\u00a7r\u00a7$1");
```
