### ISSUE TITLE
LegacyComponentSerializer#deserialize should accept a null string

### ISSUE THREAD

**Issue by Machine-Maker** [KyoriPowered/adventure#221]
In converting stuff in Paper to adventure, I found quite a few times where I had to do 
```java
Component msg = string != null ? LegacyComponentSerializer.deseralize(string) : Component.empty();
```

Just returning an empty component in the deserialize (and probably an empty string in the serializer (or null)) would simplify this process

**Comment by zml2008** [comment]
Accepting a null string would be kind of iffy for nullability annotations. Might make sense to add a method, something like:

```java
@Nullable O deserializeIfNonNull(final @Nullable R input);
```

(probably with a better method name)?

**Comment by Electroid** [comment]
I think this is a good idea. Quite universal that `null` implies an empty component.

**Comment by kashike** [comment]
In quite a few cases, I see code like this: `final Component component = string != null ? deserialize(string) : Component.empty()`... so I think this is a good idea. Just a matter of if we want to adjust the existing method, or if we add a new one like @zml2008 suggested?
