### ISSUE TITLE
Put static builder/factory methods on the interface types that they return

### ISSUE THREAD

**Issue by dualspiral** [KyoriPowered/adventure#224]
_This issue is taken from https://github.com/SpongePowered/SpongeAPI/pull/2275#issuecomment-739912355_

Currently, in order to build a `TextComponent`, you must call `Component.text(*)`, there is no way to know, based on the `TextComponent` interface itself, how to construct such an object.

Pre 4.0 gold, `TextComponent` actually had `builder` and `of` methods, which were removed in favour of static methods on `Component` named `text(*)`. From a strictly Sponge point of view, this works against the design of our API and so this works against us. I also accept that this library is not Sponge and so I'm not asking for `of` to return, as `TextComponent.text(String)` is a totally reasonable construct - I understand that you made this deicions to use `text()` et. al. as methods to support static imports. However, taking the factory method off `TextComponent` and putting it on to `Component` has caught a few of us out - personally, I feel `Component.text(...)` is the wrong place for this to go as the type you're advertising this to be is a `TextComponent`. 

Futher, from the Sponge point of view, where `Text.of()` in API 7 was a (admittedly bad) thing, that is the first place that people are going to start looking. Putting the factory and (renamed) builder methods back on `TextComponent` will aid IDE autocompletion and we're onto a winner - people **will** look for that.

Thus, I propose that the `text()/textBuilder()/whatever` factory/builder methods are put onto `TextComponent` as these methods construct `TextComponent`s, not merely `Component`s, and I suggest a similar setup for other component types.

**Comment by kashike** [comment]
> Pre 4.0 gold, `TextComponent` actually had `builder` and `of` methods, which were removed in favour of static methods on `Component` named `text(*)`.

One of the reasons we moved the methods *to* `Component` was to make everything more discoverable - similar to how the SpongeAPI used to have everything in `Text`.

> Futher, from the Sponge point of view, where `Text.of()` in API 7 was a (admittedly bad) thing, that is the first place that people are going to start looking. Putting the factory and (renamed) builder methods back on `TextComponent` will aid IDE autocompletion and we're onto a winner - people **will** look for that.

Sure, that works for `TextComponent` - but typing `Text` (assuming the person is coming from Sponge and is looking for the `Text` class) does not show the other `Component` types such as `TranslatableComponent` and others.

**Comment by octylFractal** [comment]
My opinion would be either to leave as-is, or maybe move them to their own standalone class `Components`.

**Comment by mbax** [comment]
What about keeping the current methods *and* having methods on the individual classes?

**Comment by ryantheleach** [comment]
If you had it on both, the JD for the one on TextComponents could literally reference Components, to drive people towards creating translatable components etc.

**Comment by kashike** [comment]
I do not think we'll be *moving* these methods, and I am hesitant to duplicate them in their types for a number of reasons:
- duplicate code, and lots of it
- need to remember to add methods to both places, make any changes in both places
- it promotes looking at a specific type for creation methods, and may harm discoverability of other types - we have seen more use of other `Component` types since moving the factory methods over to the root `Component` interface

**Comment by dualspiral** [comment]
I think that's reasonable. @kashike and I have had a bit of a discussion behind the scenes about this and I understand and respect this reasoning.

It's worth mentioning that I agree with the duplicate code statement - though yes, you could redirect the call through to the `Component` method, it still requires you to remember this when you add a new method. It may not be feasible.

**Comment by kashike** [comment]
I am going to close this issue as `wontfix` for now, due to the above discussion.
