### ISSUE TITLE
Missing getter for source name

### ISSUE THREAD

**Issue by ForceUpdate1** [KyoriPowered/adventure#234]
I do not know if it is intended, but there is no getter for the name.

https://github.com/KyoriPowered/adventure/blob/b991c1fc8e0ffeaca4644eaa7cf914bf8fcbd8a0/api/src/main/java/net/kyori/adventure/sound/Sound.java#L200

**Comment by zml2008** [comment]
This is intended behaviour -- to get the name associated with a `Sound`, the `NAMES` index should be used.
