### ISSUE TITLE
Component cycle when using empty components in hover events

### ISSUE THREAD

**Issue by bluelhf** [KyoriPowered/adventure#285]
When a component with no content is created, Adventure uses the TextComponentImpl.EMPTY constant instead of creating a new TextComponent. This means that if both a text and the hover event of that text have an empty component, a component cycle is created.

To fix this, we can simply remove the ternary from `Component#text(String)` and always create a new TextComponentImpl instead of referencing `empty()`.

**Comment by kashike** [comment]
Provide a stacktrace, please.
