### ISSUE TITLE
Legacy serializer: Erroneous reset added

### ISSUE THREAD

**Issue by Proximyst** [KyoriPowered/adventure#287]
### Observed behaviour

The legacy serializer adds an erroneous `§r` to the content of the component in the following snippet:

```java
var text = "&a&lP&eaper";
var component = LegacyComponentSerializer.legacyAmpersand().deserialize(text);
component.content(); // => §a§lP§r§eaper
```

This is not observed if no formatting is used prior to the colour switch, meaning it is only caused by going from e.g. bold to red without bold.

### Expected behaviour

The content should be only `P` for the first component, then another extra component under it with `aper` and their respective styles applies.

Alternatively, it should not introduce an `§r` as that is unnecessary when changing a colour, because it is implied.

---

This issue was discovered on [Paper](https://github.com/PaperMC/Paper), which packages Adventure 4.5.1.

**Comment by zml2008** [comment]
Fixed in #291
