### ISSUE TITLE
Argument Formatting

### ISSUE THREAD

**Issue by SupaHam** [KyoriPowered/adventure#3]
A limiting factor in recent years with the new JSON chat system is the ability to construct messages with arguments conveniently and safely.

In my own systems, I have implemented an XML parser that takes XML code and converts it to a JSON text object. E.g. `<span style="9">foo</span>` translates to `{"text": "foo", color: "blue"}`

I also added the ability to have parameters in messages to be given in runtime. So `<span style="9">foo {0}</span>`, with `{0}` being `"bar"`, translates to `{"text": "foo bar", color: "blue"}`.

Now, I've reached a point where parameters need to be more complicated in the form of text components. So when given `<span style="9">foo {0}</span>`, with `{0}` being a Component, translates to `{"text": "foo", color: "blue", extra: [ {"text": "bar", color: "yellow"} ] }`.

I know this falls outside of the project's scope currently as there is no ability to string format messages. However, since it is a text library I thought it might be fitting for those who wish to implement I18n-like systems or just organised messages.

XmlParser: https://github.com/BlurEngine/Blur/blob/master/src/main/java/com/blurengine/blur/text/xml/XmlParser.kt

**Comment by SupaHam** [comment]
Implemented in https://github.com/BlurEngine/Blur/commit/5c85288c985d52dec15cb2ecf1ec8a62673115d3

**Comment by zml2008** [comment]
This seems like between the various mechanisms added over the years (`replaceText`, MM, `TranslationArgument`s, etc) it should be sufficiently resolved.
