### ISSUE TITLE
Kotlin DSL isn't marked with @DslMarker

### ISSUE THREAD

**Issue by BomBardyGamer** [KyoriPowered/adventure#303]
I think you force pushed the Kotlin branch and you must've forgot to recreate the annotation annotated with `@DslMarker` to mark the DSL methods as DSL methods.

**Comment by kashike** [comment]
I did not forget - I was told that it was useless there. If you can link to some documentation that says otherwise, I will re-add it.

**Comment by BomBardyGamer** [comment]
https://kotlinlang.org/docs/type-safe-builders.html

**Comment by kashike** [comment]
That shows the annotation being applied to classes, not methods.

**Comment by BomBardyGamer** [comment]
Also, in addition to that, it makes the colour of the functions go a nice colour in IntelliJ (it goes one of four colours)

**Comment by BomBardyGamer** [comment]
Let me cite some of my own uses of the `@DslMarker` annotation

**Comment by BomBardyGamer** [comment]
https://github.com/BomBardyGamer/komponent/blob/master/src/main/kotlin/me/bardy/komponent/dsl/ComponentDSL.kt

**Comment by kashike** [comment]
I'm not asking for your code, I'm asking for official documentation that the annotation being on methods is supported.

**Comment by BomBardyGamer** [comment]
Actually, there isn't any official documentation about it, you're right. That's strange, since it's perfectly fine to annotate functions with `@DslMarker`, and it does work as intended on functions.
