### ISSUE TITLE
Conversation API?

### ISSUE THREAD

**Issue by PikaMug** [KyoriPowered/adventure#309]
Would the project consider including something similar to Bukkit's Conversation API? I'm aware that SpongeAPI has such a thing planned for Rev 8.0, but with Velocity (and Fabric) being supported Platforms it would be great to have natively.

**Comment by ItsDoot** [comment]
Just want to point out that Sponge doesn't have any plans for a conversation API for API 8.

**Comment by MiniDigger** [comment]
mmmh, that would require intercepting all other outgoing messages, protocol hackery, etc.
I guess a lib like adventure would provide the api, but the protocol stuff would be handled in the impl on the platforms.

**Comment by PikaMug** [comment]
> Just want to point out that Sponge doesn't have any plans for a conversation API for API 8.

https://github.com/SpongePowered/SpongeAPI/milestone/14 # 432

**Comment by MiniDigger** [comment]
last updated 2017, lol

**Comment by PikaMug** [comment]
There's closed issues tagged `api: 8` as recently as Dec 2020. Glad to hear it's a possibility :heart:

**Comment by zml2008** [comment]
please take a moment to read what doot has said from sponge's point. Adventure is in the same place -- this is not a hard no, but it is far from the top of anyone's list so do not expect anything to happen soon.

**Comment by zml2008** [comment]
With the trouble that the Paper folks have had even thinking about evolving their conversations API, I think it would be best to keep this sort of API out of the core of adventure, where we're more blocked from making breaking changes. However, we'd love to see any community-developed conversation libraries on our [community libraries](https://docs.adventure.kyori.net/community-libraries.html) page.
