### ISSUE TITLE
High allocations with adventure.

### ISSUE THREAD

**Issue by Agaloth** [KyoriPowered/adventure#311]
![image](https://user-images.githubusercontent.com/33335971/111505666-26e77f00-8749-11eb-83a6-8e47a01e3cc0.png)

**Comment by Agaloth** [comment]
https://flare.airplane.gg/c4764df1
Plugin used: CarbonChat

**Comment by zml2008** [comment]
Unfortunately a lot of this object churn is due to the overhead of converting Adventure components to native components outside of a native implementation. You should experience reduced overhead using the version of CarbonChat that uses Paper's native API rather than an adapter.

**Comment by zml2008** [comment]
after some further inspection, it seems there is quite a bit of object churn coming from the "itemsadder" plugin that you might want to look into:

![image](https://user-images.githubusercontent.com/629092/111506730-28905300-8707-11eb-9e8c-27f469090d3e.png)
