### ISSUE TITLE
Unexpected behavior with using the ComponentFlattener to flatten translatables(which get translated) with children

### ISSUE THREAD

**Issue by KingOfSquares** [KyoriPowered/adventure#356]
While fixing #262 I noticed some unexpected behavior when using the new `ComponentFlattener`

The following test fails:

```java
  @Test
  void testNestedTranslations() {
    final TranslationRegistry registry = TranslationRegistry.create(Key.key("key"));

    final Map<String, MessageFormat> translations = new HashMap<>();
    translations.put("dummy.welcome", new MessageFormat("Welcome "));
    translations.put("dummy.simon", new MessageFormat("Simon"));
    registry.registerAll(Locale.US, translations);
    
    final TranslatableComponentRenderer<Locale> renderer = TranslatableComponentRenderer.usingTranslationSource(registry);
    
    final Component component1 = translatable("dummy.welcome");
    final Component component3 = translatable("dummy.simon");

    final Component welcomePrompt = component1.append(component3);
    
    ComponentFlattener flattener = ComponentFlattener.builder()
      .complexMapper(TranslatableComponent.class, (t, cc) -> cc.accept(renderer.render(t, Locale.US)))
      .mapper(TextComponent.class, TextComponent::content).build();

    final StringBuilder builder = new StringBuilder();

    final FlattenerListener listener = builder::append;

    flattener.flatten(welcomePrompt, listener);

    assertEquals("Welcome Simon", builder.toString());
  } 
```

```
expected: <Welcome Simon> but was: <Welcome SimonSimon>
Expected :Welcome Simon
Actual   :Welcome SimonSimon
```

This is because when translatables is flattened in this scenario the children is flattened twice:

1.
https://github.com/KyoriPowered/adventure/blob/b90902214cf0f2cb574fbd9501fa0fd08e09a1ef/api/src/main/java/net/kyori/adventure/text/flattener/ComponentFlattenerImpl.java#L92
which leads to 
https://github.com/KyoriPowered/adventure/blob/b90902214cf0f2cb574fbd9501fa0fd08e09a1ef/api/src/main/java/net/kyori/adventure/text/flattener/ComponentFlattenerImpl.java#L124

where the component now flattened after its initial mapping to a text component still has its original children

2.
https://github.com/KyoriPowered/adventure/blob/b90902214cf0f2cb574fbd9501fa0fd08e09a1ef/api/src/main/java/net/kyori/adventure/text/flattener/ComponentFlattenerImpl.java#L95-L99

There is no easy way to prevent this since the rendered translatable is returned as a component with a empty text parent
(e.g doing `.complexMapper(TranslatableComponent.class, (t, cc) -> cc.accept(renderer.render(t, Locale.US).children(new ArrayList<>()))` would remove all rendered text)

If this is intended the ComponentFlattener should note how it expects the complexMappers to work regarding component trees. Ideally the server side translations should also work with the flattener, since it seems like a pretty obvious use of the complexMapper feature.

**Comment by zml2008** [comment]
This is intended behavior -- each mapper should operate on a component in isolation, not referencing its children.

A component should be rendered before it's passed into the flattener at all. If you absolutely must render within the flattener, it should be simple to remove all children before passing the component into the translabale renderer.
