### ISSUE TITLE
Suggestions - StyleSerializer for Legacy 

### ISSUE THREAD

**Issue by LemonCaramel** [KyoriPowered/adventure#359]
_my english is very poor. i'm using a translator, so please understand._
<br>

I'm [porting](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0010-Adventure.patch) and using Adventure on Paper 1.15.2.
Everything works fine, but I'd like to suggest something.

Even if use "legacyHoverEventSerializer" and "emitLegacyHoverEvent", elements that are not used by the legacy are included.

"contents"
![image](https://user-images.githubusercontent.com/45729082/117914140-ae9ed380-b31d-11eb-89ab-72bcf6abb421.png)

This causes increased traffic due to unused elements.
In the country where I live, the charges for the ethernet line used for the server are very high. (charge by traffic)

Therefore, I remove unused elements("contents") through the code below.
![image](https://user-images.githubusercontent.com/45729082/117916367-fcb5d600-b321-11eb-876e-20c8df8f798f.png)

This removal does not seem to be a good idea because it affects server throughput.

So I'd like you to add an option for legacy.

===

example
https://github.com/KyoriPowered/adventure/blob/8396f93d3109a61a9c7d6bd6ae35484f822ae0f3/text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/StyleSerializer.java#L241
to
```java
if (!this.isForLegacy)
    eventJson.add(HOVER_EVENT_CONTENTS, modernContents);
```

**Comment by zml2008** [comment]
Our primary target is and always will be the latest version of Minecraft. I don't think it's worth the extra complexity for something that isn't broken, and only affects older game versions.
