### ISSUE TITLE
Migrate remaining text-serializer-gson serializers to use `TypeAdapter`s

### ISSUE THREAD

**Issue by kashike** [KyoriPowered/adventure#372]
The following serialisers need some work to be converted from implementing `JsonDeserializer`/`JsonSerializer` to `TypeAdapter`:
- [ ] [ComponentSerializerImpl](https://github.com/KyoriPowered/adventure/blob/master/text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ComponentSerializerImpl.java)
- [ ] [ShowEntitySerializer](https://github.com/KyoriPowered/adventure/blob/master/text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ShowEntitySerializer.java)
- [ ] [ShowItemSerializer](https://github.com/KyoriPowered/adventure/blob/master/text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ShowItemSerializer.java)
- [ ] [StyleSerializer](https://github.com/KyoriPowered/adventure/blob/master/text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/StyleSerializer.java)

**Comment by emilyy-dev** [comment]
Self assigned over at https://github.com/emilyy-dev/adventure/tree/feature/gson-type-adapters

### Checklist from above
* [ ] <s>[`ComponentSerializerImpl`](https://github.com/emilyy-dev/adventure/blob/feature/gson-type-adapters/text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ComponentSerializerImpl.java)</s> (see note)
* [ ] [`ShowEntitySerializer`](https://github.com/emilyy-dev/adventure/blob/feature/gson-type-adapters/text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ShowEntitySerializer.java)
* [x] [`ShowItemSerializer`](https://github.com/emilyy-dev/adventure/blob/feature/gson-type-adapters/text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/ShowItemSerializer.java)
* [ ] [`StyleSerializer`](https://github.com/emilyy-dev/adventure/blob/feature/gson-type-adapters/text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/StyleSerializer.java)

### Additional changes
* Introduced a [`SerializerFactory`](https://github.com/emilyy-dev/adventure/blob/feature/gson-type-adapters/text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/SerializerFactory.java) that implements `TypeAdapterFactory` in the hopes of making it easier to pass dependencies around between the different serializers; this allows for a similar setup to the one provided by the `Json(De)SerializationContext`.
* Made a singleton out of the `TextColorWrapper.Serializer`

___

Note: the `ComponentSerializerImpl` will be left as is as of now, the variance between the different component types and the "one-way reading" constraint of the `JsonReader` makes it an obnoxiously large task, having to prepare too many unnecessary elements that may not even be required (e.g. translatable `args`, `nbtPath`, `nbt`, selector `pattern`, block NBT `pos`, etc.). Reading directly from a `JsonElement` makes it so it can cherry pick the elements as they are required.

___

I will update this comment as I push commits to my branch.
