### ISSUE TITLE
Sort of a String#replace for working with Components

### ISSUE THREAD

**Issue by Vankka** [KyoriPowered/adventure#38]
I'm looking for a way to take a config value like `%displayname%: %message%` and replace %displayname% and %message% with components (and somehow probably also parse & color codes at the same time (ex. `%displayname%&r: %message%`))

Example: (simplified for demonstration purposes, in the real world the replaced components could have click & hover events and wouldn't just be a simple text component with just content)

```
Component comp = TextComponent.of("%displayname%: %message%")
    .replace("%displayname", TextComponent.of("Steve"))
    .replace("%message%", TextComponent.of("Hello World!"));
```

**Comment by wizjany** [comment]
Use a translatable component? then you can use the friendly renderer and provider a translation function that replaces placeholders with values.

**Comment by Vankka** [comment]
Converting color codes at the same time isn't really possible as far as I can tell

**Comment by Vankka** [comment]
@lucko any response other than that one reaction? Is it going to get added eventually?

**Comment by liach** [comment]
> Converting color codes

Use textformat man

**Comment by Scarsz** [comment]
https://github.com/KyoriPowered/text/blob/master/api/src/test/java/net/kyori/text/TranslatableComponentTest.java is as about as good of an example I can find for this.

```java
var renderer = FriendlyComponentRenderer.from((locale, key) ->
        new MessageFormat("{0} and {1} are cats.");
renderer.render(
    TranslatableComponent
        .builder()
        .key("cats")
        .args(
            TextComponent.of("kashike"),
            TextComponent.of("lucko")
        )
        .color(TextColor.YELLOW)
        .build()
);
```

I'm not really a fan of using the argument index to do the substitution though... I can already see users messing it all up seeing as these messages will be user-configured. Is there anything comparable to this but with named arguments or will this need to be done by the implementing library? I feel like this would be a useful addition if there isn't something already.

```java
var renderer = FriendlyComponentRenderer.from((locale, key) ->
        new MessageFormat("{thing1} and {thing2} are cats.");
renderer.render(
    TranslatableComponent
        .builder()
        .key("cats")
        .args(
            "thing1", TextComponent.of("kashike"),
            "thing2", TextComponent.of("lucko")
        )
        .color(TextColor.YELLOW)
        .build()
);
```

**Comment by Scarsz** [comment]
This ended up being more of a pain to work around than expected. Because Kyori uses Java's [MessageFormat](https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html), named arguments aren't easily possible because MessageFormat itself doesn't support named arguments.

I worked around this by keeping track of the order of named arguments given through the definition and sending the indexed version to the MessageFormat constructor. When the rendered component is needed, it replaces the indexed MessageFormat's parameters by matching the indexes to the supplied argument array indexes.

Definitely not the cleanest solution, but seems to work well enough for my purposes. Can't give an easy to look at example because I worked the implementation into my plugin's code but you can probably get an understanding of it easily enough. https://github.com/DiscordSRV/Iris/blob/master/discordsrv-common/src/main/java/com/discordsrv/common/Text.java#L86-L160

```java
Definition KYORI_TEST_INDEX_SUBSTITUTION = new Definition("kyori.test.1",
    "{0} interacted with {1}");
Definition KYORI_TEST_NAME_SUBSTITUTION = new Definition("kyori.test.2",
    "{the first person} interacted with {the second person}");

...

@Test
public void name() {
    String testOneRendered = Text.asPlain(Text.KYORI_TEST_INDEX_SUBSTITUTION.render("Person 1", "Person 2"));
    String testTwoRendered = Text.asPlain(Text.KYORI_TEST_NAME_SUBSTITUTION.renderNamedArgs(
            "the first person", "Person 1",
            "the second person", "Person 2"
    ));

    System.out.println("Index-based substitution: " + Text.KYORI_TEST_INDEX_SUBSTITUTION.getRawFormat() + "\n-> " + testOneRendered);
    System.out.println("Name-based substitution: " + Text.KYORI_TEST_NAME_SUBSTITUTION.getRawFormat() + "\n-> " + testTwoRendered);

    Assert.assertEquals(testOneRendered, testTwoRendered);
    System.out.println("Results match");
}
```
```
Index-based substitution: {0} interacted with {1}
-> Person 1 interacted with Person 2
Name-based substitution: {the first person} interacted with {the second person}
-> Person 1 interacted with Person 2
Results match
```

**Comment by Electroid** [comment]
I've added `TextComponent#replace` method that should allow for regex search and replacement. https://github.com/KyoriPowered/adventure/commit/c6acc3c8a20ae333840bbe719492796fde611fb2
