### ISSUE TITLE
Loss of style when replacing full match text

### ISSUE THREAD

**Issue by Lignium** [KyoriPowered/adventure#387]
When replacing text with a complete match of the text of a component with another component (`ComponentLike`) without a style (primitive text without any style), the outer style is lost, although it should be inherited. If you do a partial match, such as adding spaces at the end or beginning of the original component, the style is inherited correctly.

I found the code that is responsible for this. However, I don’t know how to fix it correctly.
https://github.com/KyoriPowered/adventure/blob/e23407ac6c0d4122cc4646d2f9e9fa1328a0423a/api/src/main/java/net/kyori/adventure/text/TextReplacementConfig.java#L193-L197
https://github.com/KyoriPowered/adventure/blob/e23407ac6c0d4122cc4646d2f9e9fa1328a0423a/api/src/main/java/net/kyori/adventure/text/TextReplacementRenderer.java#L75-L76

**Comment by kashike** [comment]
Could you please provide code to reproduce this?

**Comment by Lignium** [comment]
```java
ComponentSerializer<Component, TextComponent, String> serializer = LegacyComponentSerializer.legacyAmpersand();

Component originalText = serializer.deserialize("&aHello, &c{name}&a!");
Component replacementText = serializer.deserialize("man");

TextReplacementConfig textReplacementConfig =
        TextReplacementConfig.builder().matchLiteral("{name}").replacement(replacementText).build();

Component resultText = originalText.replaceText(textReplacementConfig);

// Output: &aHello, &rman&a!
// Should be: &aHello, &cman&a!
System.out.println(serializer.serialize(resultText));
```
