### ISSUE TITLE
Merge MiniMessage

### ISSUE THREAD

**Issue by kashike** [KyoriPowered/adventure#402]
- [x] https://github.com/KyoriPowered/adventure-text-minimessage/issues/118
- [x] https://github.com/KyoriPowered/adventure-text-minimessage/issues/119
- [x] https://github.com/KyoriPowered/adventure-text-minimessage/issues/120

**Comment by Aberdeener** [comment]
LGTM, thanks.

**Comment by A248** [comment]
What does this issue mean? Is the plan to make minimessage a dependency of adventure-api or somehow included with it?

**Comment by zml2008** [comment]
just merging MM into the same repo, as a separate submodule
