### ISSUE TITLE
Typo in method name deseializeOrNull -> deserializeOrNull

### ISSUE THREAD

**Issue by marcbal** [KyoriPowered/adventure#412]
https://github.com/KyoriPowered/adventure/blob/153ec59b963a2f5987e8fd72e43c4202f6cae8b0/api/src/main/java/net/kyori/adventure/text/serializer/ComponentSerializer.java#L63
Should be `deserializeOrNull`

**Comment by zml2008** [comment]
take two seconds and read the area around that method

**Comment by marcbal** [comment]
Oops didn’t have the last version in my IDE
