### ISSUE TITLE
Audience visibility options

### ISSUE THREAD

**Issue by imDaniX** [KyoriPowered/adventure#413]
Bukkit API has a [method](https://papermc.io/javadocs/paper/1.17/org/bukkit/entity/Player.html#hidePlayer(org.bukkit.plugin.Plugin,org.bukkit.entity.Player)) to hide a player from another player. I think it would be quite cool to have something in Audience to interact with it, at least some [`canSee`](https://papermc.io/javadocs/paper/1.17/org/bukkit/entity/Player.html#canSee(org.bukkit.entity.Player)) alternative.

**Comment by kezz** [comment]
I'm not sure this makes much sense for `Audience`, considering they can represent worlds, consoles, log files, etc. Plus this seems like an awful lot of work for implementations as well as being slightly out of scope of the project overall.

**Comment by Proximyst** [comment]
I feel this is more appropriate as part of a pointer in whichever API you use, e.g. `Player#PLAYER_VISIBILITY_POINTER` in Bukkit's API.

**Comment by imDaniX** [comment]
Well, actually you're right. While in my opinion it does make *some* sense in adventure as an idea, it has nothing to do with hiding/vanish - I actually dunny why I even mentioned it. Feel free to close the issue if you want to.

**Comment by imDaniX** [comment]
Actually, let me close it myself. In the current state, this issue has no solid enhancement request and brings nothing onto the table.
