### ISSUE TITLE
Keybinds.SWAP_HANDS has the incorrect value.

### ISSUE THREAD

**Issue by harvanchik** [KyoriPowered/adventure#415]
This is not a problem with Adventure, but rather a misconception.

Running the following command in Minecraft yields this result.
`/tellraw @a ["\n\n",{"keybind":"key.swapHands"},"\n\n"]`

![image](https://user-images.githubusercontent.com/66141166/125179267-003ecf80-e1a2-11eb-9d05-2f0f81b0a4a1.png)

Whereas, running this command yields this.
`/tellraw @a ["\n\n",{"keybind":"key.swapOffhand"},"\n\n"]`

![image](https://user-images.githubusercontent.com/66141166/125179285-30866e00-e1a2-11eb-8e9c-0d7a1fba9c72.png)

You can see that the difference between the two is that the second (correct) one says "swapOffHand" instead of "swapHands."

**Comment by zml2008** [comment]
I'm sorry, what's the issue here?

**Comment by harvanchik** [comment]
> I'm sorry, what's the issue here?

I just explained it?  What do you mean?

**Comment by zml2008** [comment]
I see nothing in this issue that mentions adventure.

**Comment by harvanchik** [comment]
Yep.  Just realized it's a bungee chat API problem.  My mistake.
