### ISSUE TITLE
HoverEvent is not firing while it is added in AsyncChatEvent.

### ISSUE THREAD

**Issue by shitzuu** [KyoriPowered/adventure#417]
Today, I was trying to replace string to a component which after hover is showing item from player's hand, but I was surprised while this wasn't firing. After cancelling the event and sending message by 'Player#sendMessage' method it is working as it was supposed to do.
```java
Component component = itemMeta.displayName();
if (component == null)
{
        component = Component.text(itemStack.getI18NDisplayName() == null
                ? "Unknown name"
                : itemStack.getI18NDisplayName());
}
component = component
        .append(Component.text(" x"))
        .append(Component.text(itemStack.getAmount()))
        .hoverEvent(itemStack);

event.message(event.message().replaceText(TextReplacementConfig.builder()
        .matchLiteral("<item>")
        .replacement(component)
        .build()));
```

**Comment by kezz** [comment]
If you can confirm that this bug is present with zero other server or proxy plugins present then you need to open this issue on Paper's GitHub.
