### ISSUE TITLE
Move TextComponent.ofChildren(ComponentLike...) into Component

### ISSUE THREAD

**Issue by kezz** [KyoriPowered/adventure#418]
In line with the rest of the API having static methods on `Component`, this one should also live in `Component` and just return a `Component` instead of a `TextComponent`.

**Comment by zml2008** [comment]
hmm, i'd thought about this but got stuck on what to call the method in `Component` -- `wrap`? `of`, `text(List<? extends ComponentLike>)`?

**Comment by kezz** [comment]
could be part of #292 or maybe another collector method? otherwise, maybe `joinAsSiblings` or something?

**Comment by kezz** [comment]
Actually, it's worth noting that `Component.join(JoinConfig.noSeparators(), components)` would be functionally identical to the `ofChildren` method. My vote would be to just deprecate this method alongside #344 and mark the new `JoinConfig` system as the replacement.
