### ISSUE TITLE
Provide an alternative for `TextDecoration#as(boolean)`

### ISSUE THREAD

**Issue by kezz** [KyoriPowered/adventure#431]
On Kotlin, `as` is a protected keyword which means you can't do `TextDecoration.ITALIC.as(false)` without doing the ugly ``TextDecoration.ITALIC.`as`(false)``.

This could either exist in the API or in the Kotlin module, although preferably the former.

**Comment by kashike** [comment]
Suggestions for names?

**Comment by kezz** [comment]
`state`?
