### ISSUE TITLE
Add custom font support to text component API

### ISSUE THREAD

**Issue by demkom58** [KyoriPowered/adventure#434]
In minecraft 1.16 new tag "font" was added, that allows use custom fonts from resource packs.
Details: [wiki](https://minecraft.fandom.com/wiki/Raw_JSON_text_format#Content_types)

**Comment by kezz** [comment]
https://jd.adventure.kyori.net/api/latest/net/kyori/adventure/text/format/Style.html#font(net.kyori.adventure.key.Key)
