### ISSUE TITLE
Proper documentation/getting started guide

### ISSUE THREAD

**Issue by Andre601** [KyoriPowered/adventure#44]
Sorry to ask this through an issue, but I wonder if there is a proper site, wiki or similar to get started with this library as the Readme doesn't cover everything you might wanna know.
Like if you could create a hover text from a List and how that would be done when it is possible.

I want to use this library but the lack of explanation for (most commonly) made methods makes it a bit hard, to begin with. Especially when you just begin with those things like I do right now.

And another question I have is if there is a method to use, that would parse the raw JSON based on what server version the plugin is running on considering that there seem to be two separate types of JSON formats.

**Comment by MiniDigger** [comment]
not really a solution but the lib is unit tested so those can serve as an example:
https://github.com/KyoriPowered/text/tree/master/api/src/test/java/net/kyori/text

**Comment by Andre601** [comment]
Wouldn't it still be benefitial to have a wiki page that f.e. explains some of the more important classes, what they can (and even more important what they cannot) do and some common use examples.

I agree that the readme already explains most commonly used stuff, but things like the Hovertext are missing and maybe a section about certain limitations could also be useful.

Also another question... When I f.e. would iterate through the different lines. Could I just use the translateAlternateColorCodes method to make the hover coloured? Or would I need to use a separate method for this?

**Comment by kashike** [comment]
https://docs.adventure.kyori.net/
