### ISSUE TITLE
Compacting nested colors sometimes uses the wrong color

### ISSUE THREAD

**Issue by rymiel** [KyoriPowered/adventure#455]
I don't know the extent of the bug but at the very least: Compacting a component with nested children, where one child-of-a-child uses the color of the outer-most element will incorrectly use the color of the child instead.

Consider the following test case:

```java
  @Test
  void testSomethingIdk() {
    final Component notCompact = text("mew", NamedTextColor.RED)
      .append(text("mow", NamedTextColor.BLUE)
          .append(text("mew", NamedTextColor.RED)));
    final Component expectedCompact = text("mew", NamedTextColor.RED)
      .append(text("mow", NamedTextColor.BLUE))
      .append(text("mew"));

    assertEquals(notCompact.compact(), expectedCompact);
  }
```

Currently, this test fails because the last "mew" turns blue. 
![image](https://user-images.githubusercontent.com/53803019/135538769-ebafc9f9-418a-444a-847b-ac49695043d7.png)
The second component is joined into "mowmew" in blue, but those should never be joined as they are different colors

**Comment by rymiel** [comment]
I've noticed that swapping the order of `childParentStyle` and `parentStyle` here will produce a suboptimal tree, but at least keeps the operation as monotonic. I can't wrap my head around all of the parent and child logic but this is where the mistake is coming from; the style of red color is merged into blue with IF_ABSENT_ON_TARGET, so the blue color "wins"

https://github.com/KyoriPowered/adventure/blob/2497d92f5cf88992e6c66dac3338bb0f640bacc6/api/src/main/java/net/kyori/adventure/text/ComponentCompaction.java#L71

**Comment by zml2008** [comment]
Your change there does appear to be correct. It doesn't look like the compaction algorithm has a way to promote a child to a sibling -- adding that would probably be an interesting feature, but I'd rather prioritize correctness for now.

It seems like all other tests pass with that change though, so I think it's worth applying it for now.
