### ISSUE TITLE
The future of Adventure and Java

### ISSUE THREAD

**Issue by kashike** [KyoriPowered/adventure#456]
There have been a few discussions regarding Adventure 5.0.0 over the past few months, and one of the questions that keeps coming up is "What version of Java will we target?", so I wanted to open an issue here to gather feedback from people.

Currently, Adventure 4.x targets Java 8, as Java 8 is what Minecraft (and most modding platforms) targetted at the time. As of writing this, Minecraft is currently targetting Java 16, and it is likely that it will be targetting Java 17 soon as well.

As I see it, we have two good options:
- continue targetting Java 8
- target Java 17 (which is also LTS)

Thoughts?

**Comment by octylFractal** [comment]
I'm in favor of targeting 16/17 (whichever MC is on once 5.0.0 comes out).

**Comment by kezz** [comment]
In my opinion, 4.x is a great library in terms of usability that most developers would be more than happy to stay on it, especially with the recent release of the platform builds that mean you could continue to use 4.x for a while. As a developer, it's becoming more and more annoying to stay targeting old Java versions, considering the plethora of new features and additions in recent versions, let alone the earlier API improvements in Java 11. There are many, many reasons to bump Java versions, the main ones being records, proper immutable lists and eventually sealed classes.

I don't think we should continue letting Adventure suffer the lack of these features in 5.x, and considering Minecraft's recent bump to use recent Java versions, I would be more than happy for Adventure to follow suit and target a modern Java version in 5.x.

**Comment by clrxbl** [comment]
Targetting Java 17 / following LTS releases is the way to go.

**Comment by kennytv** [comment]
I agree with the previous comments. You should continue making (reasonable) bugfixes to 4.x for a while, so this great library isn't lost to the ages for people yet unable to move to modern Java versions with the advent of 5.x immediately, but targeting Java 17 and newer LTS is the better choice.

**Comment by Proximyst** [comment]
I favour Java 17, otherwise 11. I'd prefer an LTS release. Adventure would earn greatly by using Java 17's sealed interfaces & classes, and there is no real reason not to target an LTS release.

That being said, there is no reason for us not to maintain both 4.x and 5.x for e.g. 3-6 months. New major features would (naturally) only come in 5.x, but any fixes or smaller features would be introduced to both.

**Comment by rymiel** [comment]
I just love records and from what I've seen adventure has a perfectly record-sized hole carved out in it right now, so i'm absolutely for modern java

**Comment by rtm516** [comment]
As seems to be the consensus thus far, going to 17 presuming the next mc release will target it. If not I would probably suggest going to 11 to stick with a more up to date LTS release.

**Comment by aurorasmiles** [comment]
I think targetting Java 17 (if the next Minecraft release also does) is the way to go, and I also agree with @kennytv and @Proximyst that Adventure 4.x should still be maintained (as in: fixing bugs, no more new features/QoL updates) for a few months after 5.x is released.

If people want to use older Java Versions, they can also use older Adventure versions at their own risk and without support.

**Comment by dualspiral** [comment]
I don't think you're asking the best question here. The better question here is what versions of Minecraft do you want Adventure 5 to support and use _that_ to inform decisions. 

Ultimately, you market Adventure being a Java Edition toolset but Adventure 4 is designed to support a relatively wide set of Minecraft versions, probably back as far as 1.8? In this time, of course, Mojang have made advancements and you have the problem where you may have to compromise parts of the library to enable this backwards support. By bumping the Java version, you're effectively putting a soft limit on the versions supported - if Java 16, then 1.17, if Java 17, then we presume 1.18. While, yes, you can run older versions of new Java versions, the reality is that most people won't, and will probably stick with Java 8 until they _have_ to move. Better to just be sure that Adventure will run on the target platform.

With that in mind, I'm totally for such a move. There is the argument of minimally supporting Adventure 4.x for some time yet (and you should, as I forsee, say Forge sticking with 1.16.5 as their LTS for a little while yet - I know it kind of supports Java 17 with `--add-opens` but many will remain on java 8) but this is a great oppotunity to take out anything that flows against modern Minecraft, if it isn't really going to work on older platforms, now is the perfect time to make those breaks.

I think you should do it, with the mindset of "yeah, but I'm limiting what MC versions it targets too".

**Comment by Machine-Maker** [comment]
Gonna say Java 16/17. I don’t think adventure should move to java 17 if 1.18 isn’t on 17 (only 16), but I agree with kezz that 4.x.x is totally usable for people who need to support older minecraft/java versions.

**Comment by zml2008** [comment]
I've historically been against bumping Java version for bumping's sake, but at this point I don't have the time or interest to bother with legacy version support/adventure-platform at all really, so my primary compatibility concern is going to be the supported versions of the native implementations. At the moment, the oldest actively supported version is Sponge on 1.16.5. Once Sponge drops any version of MC that uses a Java version older than 17, I have no problem with exclusively targeting Java 17.

Our users on legacy versions should be able to continue using Adventure 4 with adventure-platform indefinitely, and if they are up-to-date they should be able to mostly be runtime-compatible with whichever environment -- the changes in 5.x will likely focus around removing things already deprecated in 4.x.

Now, wrt *which* version to target specifically: Adventure's already written, the code's there on Java 8 -- I don't see any huge pressure to bump versions, so we might as well wait to publish a release with that breaking change until we can target Java 17 as an LTS release. I know my time is limited, as is the time of many others, so we should avoid breaking changes and development environment requirement changes as much as possible -- an LTS release supports that goal, while allowing us to take advantage of modern API.

**Comment by astei** [comment]
> At the moment, the oldest actively supported version is Sponge on 1.16.5.

This isn't true - technically that award goes to Velocity, which supports versions as far back as Minecraft 1.7.2, but as of 3.0.0 does require at least Java 11. Granted, proxies are kind of a special case, but it's important to note that I adopted text and Adventure with the understanding that it would support older versions of Minecraft without too much difficulty. 

Bumping the Java version will require us to bump our minimum supported Java version in turn. I don't have any objections with moving Velocity to require Java 16 or 17, depending on what 1.18 winds up depending on. However, moving to Adventure 5 would require yet another major version of Velocity.

**Comment by theminecoder** [comment]
Bumping up to 17 (or 16 if mojang continue to be mojang) would make me very much happy.

**Comment by VytskaLT** [comment]
Would adventure-platform still support 1.8+? Since older versions can also run Java 8+ with some config options changed.

**Comment by kezz** [comment]
New versions of `adventure-platform` that will use newer versions of the standard Adventure API will need to also require on newer versions of Java. However, old platform builds will still exist if you need to use them for older platforms.

**Comment by kashike** [comment]
Based on the feedback received, Adventure 5.0.0 will be targetting Java 17.
