### ISSUE TITLE
RGB Colors only updates after reconnect.

### ISSUE THREAD

**Issue by DanHCraft** [KyoriPowered/adventure#476]
At first: I created a command to edit lore text and a EventListener to colorize book pages on BookEditEvent.

The Problem:
If I add or edit a line of lore and I put a RGB Color like `&#aaffaa` or `§x§a§a§f§f§a§a` in there, then it only shows the vanilla color from the last hex-digit of the color (here `&a` or `§a`).
The RGB Color only updates, if you have the Item in your Hotbar and reconnect to the server.
Book only show the true RGB Color only if you sign them, and it only works with the deprecated `ItemMeta::setPages(List<String> pages)` method.

I tried `Component.text(text)` and `LegacyComponentSerializer.legacyAmpersand().deserialize(text)`, but both shows the same behavior as discribed above.

Specification:
Paper: **1.17.1-latest**
Kyori Adventure API: tested with **4.8.1** (this is the version Paper uses) and **4.9.2** (latest at the moment)

**Comment by kezz** [comment]
I can't really see how this is an adventure issue. Have you confirmed this isn't an issue with Paper's implementation and usage of the adventure API? If so, can you provide more detail as to how this is specifically an adventure issue, such as the input and expected/actual output? Until then, I'll close this issue but please feel free to comment again with answers to those questions and I'll happily reopen this.
