### ISSUE TITLE
ComponentSerializer should be able to serialize Title and Sound

### ISSUE THREAD

**Issue by MiniDay** [KyoriPowered/adventure#507]
I noticed that the current ComponentSerializer can serialize Components, but it can't be used for Title and Sound.

For gson, I don't think it should be too difficult to add these two functions, but I'm not sure how to switch with plain text.

If it is not difficult to implement these functions, I think it is a useful suggestion to add them to the ComponentSerializer.

**Comment by kashike** [comment]
`ComponentSerializer` is, as named, *only* for `Component`s.

**Comment by MiniDay** [comment]
> `ComponentSerializer` is, as named, _only_ for `Component`s.


Oh, sorry, I didn't notice the fact.

so... Is there any tool in the API to serialize Title and Sound?

**Comment by kashike** [comment]
The `adventure-serializer-configurate4` module can be used, for example.
