### ISSUE TITLE
Gradient doesn't care about child components when continuing the colouring

### ISSUE THREAD

**Issue by kezz** [KyoriPowered/adventure#508]
See [this preview](https://webui.adventure.kyori.net/?mode=chat_closed&input=%3Cgradient%3Ared%3Ablue%3Ehhhhhh%3Cred%3Ehhh%20%3Cblue%3E!!!!!!%3C%2Fblue%3E%3C%2Fred%3E%20hhhhhhhhhh&st=%7B%7D&ct=%7B%7D). No matter how many `!` you add, the gradient on the second half of the line doesn't change.

**Comment by zml2008** [comment]
I can't seem to reproduce this -- in the webui, it appears that the colour does change, though it is quite subtle.

**Comment by kezz** [comment]
Yeah you're right, I can't seem to reproduce this either. Maybe I was just not looking hard enough :')
