### ISSUE TITLE
Templates with non-lowercase keys do not resolve

### ISSUE THREAD

**Issue by Ekinn7188** [KyoriPowered/adventure#514]
When deserializing a Component with a template, who's value is also a Component, the template never gets applied. The code just ignores the template. Here's an example
```java
        Component test = MiniMessage.miniMessage().deserialize("<Player>: Test!",
                TemplateResolver.templates(Template.template("Player", e.getPlayer().displayName())));
        Bukkit.broadcast(test);
```
This code outputs some text that looks like `"<Player>: Test!"`, when it should be replaced.

To show that this only happens with component templates, if the template gets changed to `Template.template("Player","abc")`;, it works perfectly fine and the output looks like `"abc: Test!"`

**Comment by MiniDigger** [comment]
addressed by https://github.com/KyoriPowered/adventure-text-minimessage/pull/191
