### ISSUE TITLE
Convert templates to “compound” tags

### ISSUE THREAD

**Issue by thiccaxe** [KyoriPowered/adventure#522]
Building on the ideas of KyoriPowered/adventure-text-minimessage#178 & KyoriPowered/adventure-text-minimessage#179 , this will greatly enhance the flexibility of templates.

new syntax for templates:
`<template>text with "bleeded" styles of template</template>regular text`

In essence, a template is no longer a string that is replaced, but a full tag.
Unlike a simple `<red>`, however, a template can contain its own styles, text, click events, translations, or even templates inside it.

i.e.: if `<template>` was defined as `<red><bold>Prefix</bold>`,
The first example would be equivalent to writing out:

`<red><bold>Prefix</bold>text with "bleeded" styles of template</red> regular text`

As previously stated, this greatly expands the flexibility of templates and improves minimesaage overall

**Comment by zml2008** [comment]
This should be fixed by #672
