### ISSUE TITLE
Add a way to prevent templates impacting remaining content

### ISSUE THREAD

**Issue by kezz** [KyoriPowered/adventure#523]
Something like `<my_template/>` which would resolve the template whilst preventing any tags inserted from bleeding into remaining strings.

Essentially shorthand for `<span><my_template></span>`, considering KyoriPowered/adventure-text-minimessage#178.

**Comment by zml2008** [comment]
This should be easy with #672 -- it just depends on the value of `Tag#allowsChildren()`. We could incorporate the same logic into the parser in order to support `/` for self-closing tags.
