### ISSUE TITLE
Annotate non-API public stuffs with `@ApiStatus.Internal`

### ISSUE THREAD

**Issue by kezz** [KyoriPowered/adventure#530]

**Comment by zml2008** [comment]
Is this covered with the latest work in #672? That would leave the `parser` package as internal, and everything else that's not package-private as public API.

The tag implementation classes are currently still public, but that should be resolved as soon as serializer changes land.

**Comment by zml2008** [comment]
For whole packages that are internal, what do we think about moving them into a specific `.internal` package, to make it extra clear that they're not public API? That would also allow people to exclude them from auto-importing in their IDEs if the annotation doesn't do that already
