### ISSUE TITLE
Item names are always cursive.

### ISSUE THREAD

**Issue by Trqhxrd** [KyoriPowered/adventure#534]
I need a little help here.
When I create a TextComponent using MiniMessage, it always becomes cursive, when I use it as an item name. 
If I Use the vanilla color codes, a color code overrides a formatting code. This does not apply in MiniMessage.
Is there some way to reset the formatting codes? I tried using the reset-tag but that did not change anything.

Does anyone have an idea?

Thanks in advance,
Trqhxrd

**Comment by ItsLeMax** [comment]
If anybody is curious on how to remove italic: You can use `<!italic>` inside the message like this:

```java
final String message = "<color:red>Test</color>";
MiniMessage.miniMessage().deserialize("<!italic>" + message);
```
