### ISSUE TITLE
Minimessage tags inside placeholders are not being parsed

### ISSUE THREAD

**Issue by SoSeDiK** [KyoriPowered/adventure#548]
According to [the docs](https://docs.adventure.kyori.net/minimessage.html#placeholder), minimessage tags should be parsed after custom placeholders.
So something like this should work:
```
MiniMessage.get().parse("<gray>Hello <name>", "name", "<red>MiniDigger");
```
However, the code above produces raw `<red>MiniDigger` text, not coloring it in red.
This behavior should be fixed and unit tests for it added.

*Also, as a side note, the code example in the docs should be updated. There's a missing semicolon on line 2 and redundant \<name\> on line 5 (since we provide a map).*

**Comment by kezz** [comment]
Fixed in https://github.com/KyoriPowered/adventure-text-minimessage/commit/88f0043d229c217f431d36ffdf205b76caf5c09c
