### ISSUE TITLE
Assistance with this library

### ISSUE THREAD

**Issue by Andre601** [KyoriPowered/adventure#56]
I'm currently working on a library which would allow text to be translated into TextComponents, using this library.
But I'm currently stuck at a way to make this as efficient as possible, which is why I ask now for some assistance if possible.

My library would allow to have some text like `Hello. Do you know [Google](hover:{text:["Click me!"]},click:{url:"https://google.com"})?` which would look for any appearance of `[text](text)` and translate those into TextComponents with hover and/or click events set, before adding the remaining text and returning a TextComponent containing the whole text with the above-mentioned changes (So the text would mostly stay normal while the word "Google" would have hover and click actions)

My biggest struggle is not how to get the text to add actions to (I have a Pattern made for this that should work) but how to combine the normal text with the changed text to return as a TextComponent.
Any help is greatly appreciated and if needed can I provide additional information.

**Comment by Narimm** [comment]
I think this issue is now covered by the inclusion of Minimessage and can be closed.

**Comment by Andre601** [comment]
Not quite sure, but I don't use this lib here anymore so closing this.
