### ISSUE TITLE
Pixel width

### ISSUE THREAD

**Issue by kashike** [KyoriPowered/adventure#59]
The ability to find the pixel-width of a single character, or the content of an entire component (and children).
```java
public interface PixelWidthSource {
  int width(final @NonNull Component component);

  int width(final char character);
}
```

**Comment by Electroid** [comment]
My project has an implementation for pixel width you or anyone are free to use, modify, or redistribute: 

https://github.com/Electroid/PGM/blob/389839a654c267df55113a32377e1d06a73c4b8e/util-bukkit/src/main/java/tc/oc/util/bukkit/component/ComponentUtils.java#L17 (or anything else in the linked class)

**Comment by zml2008** [comment]
Based on discussions in #262, we've decided this makes more sense to be released as an external library, unless Mojang changes what they offer us.
