### ISSUE TITLE
Tag convenience aliases

### ISSUE THREAD

**Issue by zml2008** [KyoriPowered/adventure#599]
Right now tags only really accept one name -- for flexibility and shorter templates it'd be nice to have some aliases.

- [ ] Support `<colour>` and `<c>` as an equivalent to `<color>`
- [ ] Support `<b>` as an equivalent to `<bold>`
- [ ] `<em>` and maybe `<i>` for `<italic>`
- [ ] `<tr>` for `<lang>`

thoughts on others?

**Comment by Andre601** [comment]
Is minimessage now part of default adventure, or why was this issue transferred?

**Comment by NoahvdAa** [comment]
> Is minimessage now part of default adventure, or why was this issue transferred?

Minimessage is in the process of being moved into the main adventure repo, transferring issues is the first step.
