### ISSUE TITLE
Word wrapping

### ISSUE THREAD

**Issue by kashike** [KyoriPowered/adventure#60]
The ability to word-wrap a component to a specific width - would most likely require #59.
```java
public interface WordWrapper {
  @NonNull List<Component> wordWrap(final @NonNull Component component, final int width);
}
```

**Comment by Phoenix616** [comment]
Tbh. when I read wrapping I think more of the width in characters of a line and not the pixel width. Imo. both have their use cases (and normal character count might be easier to implement first) and it would probably be good to properly differentiate those two methods.

Main issue with wrapping would be components that don't have a specific length (e.g. translatable ones, for those the default locale or a user provided one could be used to determine the length/width though), best would probably to split before that component in case it gets close to the end (maybe half-width with a minimum assumed per component or something like that)

**Comment by zml2008** [comment]
Based on discussions in #262, we've decided this makes more sense to be released as an external library, unless Mojang changes what they offer us.

**Comment by Minikloon** [comment]
https://gist.github.com/Minikloon/e6a7679d171b90dc4e0731db46d77c84
