### ISSUE TITLE
minimessage feature request: "<br>" or "\n" for multiline lores and messages

### ISSUE THREAD

**Issue by TauCubed** [KyoriPowered/adventure#619]
Add the tag `<br>` or parse `\n` correctly to allow the creation of multiline lores and messages.

This doesn't currently seem to be possible.

**Comment by kezz** [comment]
I don't think this will be something that we will support in MiniMessage. You can easily split the input string around a newline and serialise them all separately. Changing newlines to output a list of components would be a pretty big breaking change, not to mention we'd need some sort of alternative method to allow people to serialise messages without splitting into a list, which wouldn't be pretty and would be an awful lot of work compared to just making the developer split on newlines before parsing.

**Comment by TauCubed** [comment]
I'm not asking to implement conversion to a component list or anything like that.
Just a change to avoid unneeded boilerplate to convert `<br>` or `\n` to linefeed

From my testing with hover events and chat the client seems to play nice with this.
![image](https://user-images.githubusercontent.com/35522873/144499827-321a4dfb-8bfe-4598-84d0-ccecaba6c804.png)

**Comment by kezz** [comment]
MiniMessage handles newlines in input totally fine. Lore does not use newlines and does not parse them correctly, hence why a solution from MM for this would require a different method for producing a list of components as output.

**Comment by OskarZyg** [comment]
Isn't there some kind of split function where you can just split the component at each newline?

**Comment by kezz** [comment]
There's an open issue for it, yes.
