### ISSUE TITLE
Started using Adventure, can't colorize my strings from lang files.

### ISSUE THREAD

**Issue by Acixsi** [KyoriPowered/adventure#624]
I would like to know if there's a method to colorize my strings from my lang files (.properties) in Adventure. We now use the **colorize** method to do this, but with Adventure that one can't be used of course. I have been searching on the internet for quite a while now, but unfortunately I can't find anything, other than the LegacyComponentSerializer. But that one only serializes my first '#' and then not uses the numbers and letters afterwards to colorize it. We also have some hex color codes further on in our strings, and those are completely ignored.

Hope to find a method for this! 

```java
    private static final Pattern HEX_PATTERN = Pattern.compile("#([a-fA-F0-9]{6})");

    public static String colorize(String string) {
        return translateAmp(translateHex(string));
    }

    private static String translateAmp(String string) {
        return ChatColor.translateAlternateColorCodes('&', string);
    }

    private static String translateHex(String original) {
        Matcher match = HEX_PATTERN.matcher(original);
        StringBuilder builder = new StringBuilder();
        int end = 0;

        while(match.find(end)) {
            int start = match.start();
            builder.append(original, end, start);
            end = match.end();
            builder.append(ChatColor.of(original.substring(start, end)));
        }

        return builder.append(original.substring(end)).toString();
    }
```

**Comment by TheMolkaPL** [comment]
You would have to use [MiniMessage](https://docs.adventure.kyori.net/minimessage).

**Comment by zml2008** [comment]
This js an issue tracker, not a support forum. Please direct support queries to our Discord or IRC channel.
