### ISSUE TITLE
Abstract out common logic between rainbow, gradient, and transition transformations

### ISSUE THREAD

**Issue by zml2008** [KyoriPowered/adventure#636]
currently they share a lot of logic, and a lot of the same bugs

**Comment by rymiel** [comment]
Note that rainbow uses a different lerp algo and can't directly be rewritten as a <gradient> with gradient's current implementation. I thought there was already an issue for it, but it seems it was only discussed on discord (cf. [some discord messages](https://canary.discord.com/channels/319355592605040642/420342659115122688/894598292170752050), i believe @kezz had something in progress at some point)
Plus there's the issue of the phase argument and such

**Comment by zml2008** [comment]
There's also some color parsing logic shared between these 3 tags and the `color` tag, which would be worth extracting somewhere shared as well.
