### ISSUE TITLE
Placeholder aliases

### ISSUE THREAD

**Issue by kezz** [KyoriPowered/adventure#644]

**Comment by rymiel** [comment]
Is this related to #522?

**Comment by zml2008** [comment]
sorta, but based on [today's discussion](https://canary.discord.com/channels/319355592605040642/727390320677093429/920757411734782013) i think we're going the opposite direction: converting all tags/transformations into placeholders

**Comment by zml2008** [comment]
With #672 this should be doable with a custom tag resolver.
