### ISSUE TITLE
TextReplacementRenderer does not replace in click event values

### ISSUE THREAD

**Issue by Phoenix616** [KyoriPowered/adventure#666]
`Component#replaceText`/`TextReplacementRenderer` currently only replaces replacements [in hover event values](https://github.com/KyoriPowered/adventure/blob/master/api/src/main/java/net/kyori/adventure/text/TextReplacementRenderer.java#L157-L164) but not in click event values.

**Comment by zml2008** [comment]
Works as intended, click event values are not  `Components`, so the existing replacement logic cannot work.

**Comment by Phoenix616** [comment]
So what's the intended solution here? Use a third party replacement tool? (Also my apologies for opening an issue duplicate to #236, hope that one can get resolved)

**Comment by zml2008** [comment]
I suppose -- even hover events are debatable for replacement, we'll likely be adding a flag to `TextReplacementConfig` to choose whether or not to replace within hover events.

**Comment by kezz** [comment]
Phoenix, you know you have a third party tool you can use. Either submit a PR fixing 236 that works with the existing framework (a flag would be great) or just drop a lil emoji reaction on that issue if you want to lend your support to it.

**Comment by Phoenix616** [comment]
Of course I have a tool for that, just expected Component#replaceText to replace every occurrence of a placeholder and thought this was an oversight. (Also I ultimately want to move away from having to use my own custom replacement stuff so Improving this is definitely in my interest. Gonna move the conversation regarding how to best implement it over to the other issue though)
