### ISSUE TITLE
Line Breaks in Hovers don't work (anymore)

### ISSUE THREAD

**Issue by Joo200** [KyoriPowered/adventure#686]
It's not possible to create a line break in a hover: 
`<hover:show_text:Text with \nline break>My text</hover>` doesn't create the line break in the hover, it rips the message apart to
```
<hover:show_text:Text with
line break>My text</hover>
```

Suggested (and a good solution for me) from @zml2008 is:
Add a new tag `<br>` for line breaks.  This should solve the issue.

Alternatives:
* Use a varargs concept, but there are some other places where this doesn't work. And you can't add a line break outside the hover text
`<hover:show_text:'<red>First line':'<yellow>Second line'>Text</hover>`
* Get `\n` back to work.

**Comment by kezz** [comment]
Newlines do work correctly in hover events - MiniMessage doesn't touch newlines at all. Do you have a code example (not webui, that handles newlines differently) of this not working?

**Comment by MiniDigger** [comment]
This always comes back, we got explicit unit tests to make sure this doesn't break, most likely the way how you load the message into minimessage is the issue, so a minimal reproducible example is needed here.

**Comment by Joo200** [comment]
Yes, you're correct. Somehow "something" split the message before it.

I'm using a modified version of acf (replaced the string stuff with adventure) and somehow missed to remove the stuff there.
Using MiniMessage directly worked now.

Maybe the implementation of `<br>` could help here. With the new Tags it should be easy to implement (I already implemented and tested it locally).

**Comment by kezz** [comment]
Feel free to submit a PR! There does seem like a demand for a newline-inserting tag, especially considering how annoying it can be to write newlines in various markup languages.
