### ISSUE TITLE
Re-assembling chained-components doubles the contents

### ISSUE THREAD

**Issue by jaylawl** [KyoriPowered/adventure#691]
Just wondering if this is intended behaviour:

```
                GsonComponentSerializer gsonComponentSerializer = GsonComponentSerializer.gson();
                String jsonString = "[\"\",{\"text\":\"abc\",\"color\":\"dark_blue\"},{\"text\":\"de\",\"color\":\"blue\"},{\"text\":\"fghi\",\"color\":\"green\"},{\"text\":\"jklm\",\"color\":\"dark_purple\"},{\"text\":\"nop\",\"color\":\"light_purple\"},{\"text\":\"qrs\",\"color\":\"red\"},{\"text\":\"tuv\",\"color\":\"dark_red\"},{\"text\":\"wx\",\"color\":\"gold\"},{\"text\":\"yz\",\"color\":\"yellow\"}]";
                Component component = gsonComponentSerializer.deserialize(jsonString);
                commandSender.sendMessage(component);
                List<Component> list = new ArrayList<>();
                component.iterable(ComponentIteratorType.DEPTH_FIRST).forEach(list::add);
                commandSender.sendMessage("component amount: " + list.size());

                Component rebuiltComponent = Component.text("");
                for (Component c : component.iterable(ComponentIteratorType.DEPTH_FIRST)) {
                    rebuiltComponent = rebuiltComponent.append(c);
                    commandSender.sendMessage(c);
                }
                commandSender.sendMessage("rebuilt component: ");
                commandSender.sendMessage(rebuiltComponent);
```

Result:
https://i.gyazo.com/c56bdee7ce3d1dc5687f0cceafb2db34.png

Expected result was for the `rebuiltComponent` to be re-assembled the same as `component`

paper:
```
This server is running Paper version git-Paper-399 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d4318a6 on ver/1.17.1)
You are 10 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-388 (MC: 1.17.1)
```

Thank you

**Comment by kezz** [comment]
Component iterating will give you components with their children as well. So here, you're adding the root component (with all the children) and then adding all the children as well, thus duplicating everything.

**Comment by jaylawl** [comment]
Indeed, discarding index 0 fixes this. Thank you
Despite being understandable why it would be that way... dare i say it: documentation please? 😄

**Comment by kezz** [comment]
It iterates through each component. This obviously includes the root component, as it is a component as well. Just like how any tree iteration will iterate through all nodes, even the root one. Not sure what/how we'd document more here.

**Comment by jaylawl** [comment]
Well, it may be obvious to you, but wasn't to me - to the point of me hard-crashing my test server and opening an issue. Putting information like that the javadocs would spare people that aren't as well-versed as y'all a bunch of trouble.

**Comment by kezz** [comment]
If you can think of a good way to word this then feel free to submit a PR.
