### ISSUE TITLE
Gradients are asymmetrical

### ISSUE THREAD

**Issue by TauCu** [KyoriPowered/adventure#694]
**When creating a gradient with minimessage the produced colors are asymmetrical**

When creating the following gradient `<gradient:red:green:blue>123` It would be reasonably assumed that 1, 2 and 3 are red, green and blue respectively. 
In reality however `1` is red `2` is green and `3` is a slightly darker green as shown below:
![image](https://user-images.githubusercontent.com/35522873/155102148-bb2a035e-94b0-4167-8474-020a479801a5.png)

I have also tested this in the webui with the same results.

When using a larger string it is also observable:
![image](https://user-images.githubusercontent.com/35522873/155102798-e0273ec6-24c3-4f0d-938f-ab09b59f01ad.png)

**Comment by MiniDigger** [comment]
seems like the last color is basically exclusive, not inclusive

**Comment by imDaniX** [comment]
![изображение](https://github.com/KyoriPowered/adventure/assets/18292506/82aa7c92-dc3a-4c56-a654-e92f81455aea)
Seems to be fine now.
