### ISSUE TITLE
Support self-closing tags in the parser

### ISSUE THREAD

**Issue by zml2008** [KyoriPowered/adventure#704]
To be able to distinguish between components with no children and components who have all following content as a child, we should be able to have `<tag/>` be equivalent to `<tag></tag>` in the parser and serializer.

This would fully close #523.

**Comment by kezz** [comment]
This would technically be a breaking change, right? So, `<hi:Cool/>` would be handled completely differently before/after this feature is implemented. Do we want to get it in before 4.10.0 or just have some way of handling it in the parser? Perhaps a warning that it will be handled differently in the future?

**Comment by zml2008** [comment]
ugh, I suppose - it's likely not that hard to implement so let's 4.10 this again
