### ISSUE TITLE
Rename `Context#parse` to `deserialize`

### ISSUE THREAD

**Issue by kezz** [KyoriPowered/adventure#705]
Should be consistent with the main serializer.

**Comment by Joo200** [comment]
should Context#parse be deprecated or entirely removed?
I would add this to https://github.com/KyoriPowered/adventure/pull/701

**Comment by zml2008** [comment]
Just remove it, MM is still fully changeable until we reach a 4.10.0 release

**Comment by Joo200** [comment]
Another suggestion: Maybe Context should implement MiniMessage instead.
Maybe escapeTags and stripTags is useful too.

**Comment by zml2008** [comment]
I think that would be overly coupling the behavior of the two interfaces. We could eventually expose the `MiniMessage` instance directly on `Context` if users have specific things they need, but we'd rather start minimal and just add functionality as users bring up use cases.
