### ISSUE TITLE
Better exception message for legacy formatting in a MiniMessage string

### ISSUE THREAD

**Issue by kezz** [KyoriPowered/adventure#720]
At the moment, the message says:

> net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information.

Instead, it should be clearer and mention that the formatting codes have been detected _in a MiniMessage string_ instead. Could it even point to the specific part?

**Comment by zml2008** [comment]
> Could it even point to the specific part?

it already does

the wording change would be good though
