### ISSUE TITLE
Message file to class parser

### ISSUE THREAD

**Issue by masmc05** [KyoriPowered/adventure#724]
Just a possibility to make classes like with jackson or snakeyml,  but in the file instead of having strings, because the user typed a string, to have components, or completable components, i think it'll be ok if the class will need to have only fields with type: components, completable components, or another class anotated with @MessageClass 

CompletableComponent: 
i think it'll be cool to introduce at the same time this think, it's not a valid component, but can return one
its meaning is to mark that the component has placeholders inside, and has method to get a valid component, after replacing all placeholders with given components
i think it should have 3 methods
CompletableComponent#apply(HashMap<String,Component>) - this returns the component with all placeholders replaced (the map should contain the values to replace), the same as bellow, with a function (string) -> null
CompletableComponent#apply(HashMap<String,Component>, Function<String,Component>) - this is the same as above, but for all placeholders that weren't supplied, it calls the function to supply them (useful if having a PAPI that could give values for placeholders)
CompletableComponent#getFound - just returns all necessary placeholders 

MessageClass anotation: 
a simple anotation to mark that the class contains only Components, CompletableComponents, and other classes with this anotation, useful to split messages into categories 

For bukkit: 
it would be great if interaction with PAPI would be easy

For fabric/forge:
would be cool an integration with cloth config (and their auto config), and as i saw that you plan an introducing auto-completions, would be cool with an anotation to field to be able to mark available placeholders, so completions would be able to show them to user

**Comment by Joo200** [comment]
You should take a look at MiniMessage:
https://docs.adventure.kyori.net/minimessage/index.html#

That's already a good way to parse messages from strings and add placeholders.

**Comment by masmc05** [comment]
yeah, but in files it is a string, so parsing automatically mini messages to components would be very useful

**Comment by kezz** [comment]
This sounds like a neat idea, but is definitely out-of-scope of the Adventure project. If you do end up making something like this, please feel free to submit a PR to our documentation repo to add your library to the [Community Libraries page](https://docs.adventure.kyori.net/community-libraries.html)!
