### ISSUE TITLE
Action bar messages?

### ISSUE THREAD

**Issue by PikaMug** [KyoriPowered/adventure#748]
Would the project consider including the ability to send messages to the action bar, as pictured:

![Action Bar](https://i.imgur.com/QYvRTRA.png)

**Comment by zml2008** [comment]
already exists

**Comment by PikaMug** [comment]
> already exists

Would you mind clarifying? I don't see this in the documentation.

**Comment by zml2008** [comment]
this is an issue tracker, not a support forum
