### ISSUE TITLE
Message generalization

### ISSUE THREAD

**Issue by ghost** [KyoriPowered/adventure#750]
Adventure threats messages very specifically - every way of sending message has corresponding method. This is very common-sense approach and there is nothing to change here, but what about adding parallel approach and provide some abstraction over messages and message processors.

Here is the example.
In configuration we have some messages specified, but they are not the same type. However we know their type. Ex. a developer wants to send a message when an achievement is completed and they want to able user to send both title messages and chat messages to not limit the user. They must make some abstraction by their own that includes messages and content that they share, their send methods ex. component can be handled like a chat message or action bar message or part of a title. Why to not provide an abstraction in adventure api.

Structure:
I think the structure needs to be very open and simple.

If I want to send component as action bar content to audience I can
audience.send(Message.component(component, ACTION_BAR))

Or if I want to send a title.
audience.send(Message.title(title))

it does the same as
audience.showTitle()
and
audience.sendMessage()

, but it can be deserialized easly from configuration ex. (JSON)
{
"message":"Component",
"send-as":"action_bar",
"content":"<green>Hello, <player>!</green>"
}
{
"message":"Title",
"title":"<yellow>Congratulations!</yellow>",
"subtitle":"<green>Achievement Completed"
}

And how it could be handled:

final ComponentMessage = Message.raw(config.content()).proccess(minimessageProcessor.args("player", playerName), SendMethod.of(config.sendAs()));
audience.send(componentMessage);

Please tell me what you think about it. I am eager to help you or I can also develop for my own and only ask you for some concept if you do not have bandwith for that.

**Comment by kezz** [comment]
Thanks for the suggestion - this sounds better suited for a community library https://docs.adventure.kyori.net/community-libraries.html
