### ISSUE TITLE
Expanding the Key API by adding methods to check if a string may be parsed into a Key

### ISSUE THREAD

**Issue by VegetalDev** [KyoriPowered/adventure#773]
Basically what the title says.

From what I've seen, the only way to check if a string (or `namespace:value` combination) is a valid Key is by:

1) Duplicating the validation logic in KeyImpl 
2) Using exception handling as a control flow mechanism, e.g.

```java 
public static boolean isValidKey(String namespace, String value)
    try {
        Key.key(namespace, string);
        return true;
    }
    catch (InvalidKeyException ignored) {
        return false;
    }
}
```
Both of these options work, but aren't particularly elegant in my opinion. Instead, it would be better if the Key interface included `isValidKey`-like methods corresponding to the `Key#key` overloads. 

This would be primarily useful for validating user input.

**Comment by kezz** [comment]
Sounds great, exposing a regex + method to validate would be very helpful!

**Comment by kezz** [comment]
Sounds great, exposing a regex + method to validate would be very helpful!
