### ISSUE TITLE
Get component content

### ISSUE THREAD

**Issue by Azodox** [KyoriPowered/adventure#787]
Hey,

I don't know if this feature already exists but I think it's essential to have a method that returns the content of a component as a String.
Yes. Currently, there is no method (as far as I know) to get the content of a component and that restrains me in a lot of cases.

For example, if I wanna split a message sent in the chat I cannot (because Component has no split method as String does or no way to retrieve a String).

Please tell me if this could be an added feature or at least if there is an equivalent.

**Comment by zml2008** [comment]
Not all components have contents known serverside, so there is no canonical string representation.

See Component Flattener, PlainTextComponentSerializer, or MiniMessage for alternatives with different tradeoffs.
