### ISSUE TITLE
Merge text message and json message

### ISSUE THREAD

**Issue by RealHeart** [KyoriPowered/adventure#794]
```kotlin
val msg = Component.text(base)
commands.forEach {
            msg.append(Component.text(" "))
            val click = Component.text(it.message)
            click.hoverEvent(HoverEvent.showText(Component.text(it.hover)))
            click.clickEvent(ClickEvent.runCommand(it.command))
            msg.append(click)
 }
player.sendMessage(msg)
```

adventure result:

![image](https://user-images.githubusercontent.com/24838944/177462277-d9bb2a2f-11b6-4ea3-a89b-bf1c01f874b8.png)

normal result:

![image](https://user-images.githubusercontent.com/24838944/177462449-3d803da3-6149-42c4-a7cd-36d0a13a23b5.png)

**Comment by zml2008** [comment]
Read the JD for the methods you're calling.

**Comment by BomBardyGamer** [comment]
Components are immutable, so calling `hoverEvent` or `clickEvent` is creating a new component. You're discarding the result, so the new components with the click and hover event you specified just gets thrown away. Pretty sure this is on the first page of the wiki, and it's really clearly described in the JavaDocs, as zml pointed out.
