### ISSUE TITLE
Activate or deactivate the verification of old minecraft color codes

### ISSUE THREAD

**Issue by pedrokarim** [KyoriPowered/adventure#795]
This is not really a problem, but I wanted to know if it was possible to enable or disable the verification of old minecraft color formatting codes on mimi-message.

I found myself in a little problematic a bit tedious. I have a system that allows to load minecraft json files where in there are the old minecraft formatting codes but I was thinking that there would be an option to disable this check but it seems that not! 

![](https://img.ascencia.re/zsBWulQP.png)
_Small picture to understand what I am talking about!_

**Comment by kezz** [comment]
No, there is not an option and never will be.

If you have legacy, the optional thing to do is to migrate your config to use MiniMessage by deserializing using the legacy serializer and then deserializing using MiniMessage. If you need further help, jump into our Discord!
