### ISSUE TITLE
Component compaction removes colours on whitespace components with underline/strikethrough

### ISSUE THREAD

**Issue by kezz** [KyoriPowered/adventure#796]
As both of these decorations use the colouring, this is a bug.

Perhaps the solution here is to just not strip colour for whitespace? Especially considering the fact that whitespace can actually be coloured anyway if a resource pack is set up to provide visible glyphs.

**Comment by rymiel** [comment]
This seems like a duplicate of #780, the fix of which, #782, hasn't made its way into a release yet

**Comment by kezz** [comment]
kezz look at issues before opening new ones challenge (impossible)
