### ISSUE TITLE
Color codes bugged

### ISSUE THREAD

**Issue by sunnydive** [KyoriPowered/adventure#797]
**Mythic Mob Plugin**

  - '&8&m                 &r&8[ &b&lINFO&r &8]&8&m                 '
  
  This line doesn't seems to have any error, but it turned out different in the picture below. The gray line turned white.
![Untitled design (1)](https://user-images.githubusercontent.com/87953622/179923574-7ac7bc24-905f-47d4-b0f0-202ed98f5b58.png)

**Comment by zml2008** [comment]
how is this related to adventure?

**Comment by sunnydive** [comment]
I went to Mythic mob discord the support says it's a known issue that's related to kyori adventure, I've got no idea too that's why i came here to ask. They said it should be fixed by kyori 4.12 but idk the release date of it.

**Comment by zml2008** [comment]
no idea what they're on about, but if whatever they said is true this issue would already be solved.

if someone from mythicmobs wants to file an actual bug report with reproduction steps we can work with that, but there's not enough information in this issue to go off of
