### ISSUE TITLE
I need a jar for adventure

### ISSUE THREAD

**Issue by asdu5asg6da8sjd** [KyoriPowered/adventure#798]
I use eclipse, And eclipse does not use maven or grandle, I just need a compiled jar file to use in my build path.

**Comment by kezz** [comment]
Eclipse does provide plugins for both maven and gradle. However, if you don't want to use these you can download the jars directly from maven central.

**Comment by ANDREI12333** [comment]
Uh, Could i get a message from someone? Like a collaborator, Or the author.

**Comment by kezz** [comment]
No. If you want support with build issues you can come to the off-topic channel in our discord.

**Comment by asdu5asg6da8sjd** [comment]
@kezz Thank you!
