### ISSUE TITLE
`MiniMessage#escapeTags` throws an exception when input contains section symbols

### ISSUE THREAD

**Issue by JRoy** [KyoriPowered/adventure#799]
i want to be able to take untrusted user input which may contain legacy section symbol color codes and sanitize and tags from them before converting the section symbols to tags (because vise versa would cause the converted tags to be escaped)

**Comment by MiniDigger** [comment]
mmmmh, not sure why MiniMessage would care about any other format, especially unsupported legacy ones. there is no code in MiniMessage to convert legacy stuff either.
if you manually call the legacy serializer to convert legacy stuff, sanitizing that is on you, no?

basically, i don't understand the usecase, can you provide more context?

**Comment by JRoy** [comment]
> mmmmh, not sure why MiniMessage would care about any other format, especially unsupported legacy ones. there is no code in MiniMessage to convert legacy stuff either.
> if you manually call the legacy serializer to convert legacy stuff, sanitizing that is on you, no?
> 
> basically, i don't understand the usecase, can you provide more context?

Take for example chat in Essentials. It has a format in the form of a translation string and multiple arguments that are passed to it: display name, prefix, chat message, etc. Because it has user supplied input, we have to sanitize it for tags but the chat message, display name, and prefix all may have section symbols in them. I understand they're not supported in the *parser* which is why I already wrote code to convert section symbols to minimessage but I obviously can't do that before I escape tags since that would lead to the converted message being escaped by eacapeTags

**Comment by kezz** [comment]
Sounds like you want to use an unparsed placeholder tag resolver?
