### ISSUE TITLE
MiniMessage <font> can't be applied to bossbar

### ISSUE THREAD

**Issue by Xiao-MoMi** [KyoriPowered/adventure#802]
![image](https://user-images.githubusercontent.com/70987828/180933549-92c1f157-2ba6-4268-9ad4-4657a1bd62e0.png)
![image](https://user-images.githubusercontent.com/70987828/180933663-00a92a18-7c40-4de1-b043-e0610c7821a8.png)

**Comment by KingOfSquares** [comment]
This is using a vanilla client, right?

**Comment by Xiao-MoMi** [comment]
> This is using a vanilla client, right?

Yes. Vanilla 1.18.2

    Current: git-Purpur-1613 (MC: 1.18.2)*
    implementation("net.kyori:adventure-api:4.11.0")
    implementation("net.kyori:adventure-platform-bukkit:4.1.1")
    implementation("net.kyori:adventure-text-minimessage:4.11.0")

**Comment by zml2008** [comment]
![Image](https://user-images.githubusercontent.com/629092/200240753-e3e73798-f8f5-433b-8bfd-c60eb25acfd2.png)

Cannot reproduce on 22w43a, with adventure 4.11.0
