### ISSUE TITLE
issue while parsing SNBT

### ISSUE THREAD

**Issue by nostalfinals** [KyoriPowered/adventure#805]
### Infomation
```kotlin
implementation("net.kyori:adventure-platform-bukkit:4.1.1")
implementation("net.kyori:adventure-api:4.11.0")
implementation("net.kyori:adventure-text-minimessage:4.11.0")
```
### Issue
My code:
```kotlin
CorePlugin.instance.config.getString("chatFormat.itemShow.placeholder")?.let { event.message.replace(it, "<hover:show_item:${event.player.inventory.itemInMainHand.type.toString().lowercase()}:1:'$nbtString'><aqua><u>查看物品</u></aqua></hover>") }
```
The left quoto will be paired with first apostrophe in the nbt string, so it will cause issue like this:
`Failed to parse tag: {Damage:0,Enchantments:[{id:"minecraft:unbreaking",lvl:3s},{id:"minecraft:efficiency",lvl:5s},{id:"minecraft:silk_touch",lvl:1s},{id:"minecraft:mending",lvl:1s}],RepairCost:15,display:{Name:'{"text com.mojang.brigadier.exceptions.CommandSyntaxException: Unclosed quoted string at position 197: ...me:'{"text<--[HERE]`

**Comment by kezz** [comment]
Your nbt string is incorrectly formatted. Please head into our Discord if you need further support as it's easier than github issues.
