### ISSUE TITLE
Adding an empty list as children to component doesn't result in `Component.empty()`

### ISSUE THREAD

**Issue by diogotcorreia** [KyoriPowered/adventure#807]
Creating a component with
```java
Component.text("").children(Collections.emptyList())
```
does not result in `Component.empty()`.

![image](https://user-images.githubusercontent.com/7467891/182494623-0d546187-332f-4bdb-992c-b459e8f884d1.png)
```java
Component.text("").children(Collections.emptyList()) == Component.empty()
// returns false, but should be true
```

Using Adventure 4.11.0.

This doesn't seem very logical at first, but I have a component that I don't know anything about and that I set its children to a List that I also don't know anything about, so sometimes it might result in an empty component.

**Comment by diogotcorreia** [comment]
Setting the content to empty on a non-empty component also has the same behaviour:
![image](https://user-images.githubusercontent.com/7467891/182495223-910a5983-e016-402b-907a-223e795b0d20.png)

**Comment by Machine-Maker** [comment]
Don’t use reference equality, use the .equals method

**Comment by diogotcorreia** [comment]
@Machine-Maker The thing is, I am not using either `.equals` or `==` directly. Adventure's internals are using `==`, such as here:
https://github.com/KyoriPowered/adventure/blob/d32ab6b28f7ff43b0d1c89ca2a886c2a34b2d696/api/src/main/java/net/kyori/adventure/text/TextComponentImpl.java#L50
https://github.com/KyoriPowered/adventure/blob/d32ab6b28f7ff43b0d1c89ca2a886c2a34b2d696/api/src/main/java/net/kyori/adventure/text/Component.java#L128

This then causes `.compact()` to not behave as expected.

Also, found another one:
![image](https://user-images.githubusercontent.com/7467891/182497346-88593428-d73f-47b7-9d90-778f959bed4a.png)
