### ISSUE TITLE
escapeTags doesnt works correctly

### ISSUE THREAD

**Issue by xhyrom** [KyoriPowered/adventure#821]
I'm using `miniMessage.deserialize(miniMessage.escapeTags(playerChatEvent.getMessage()))` but when i use `<<aqua> a` it will escape tags but not correctly 
![image](https://user-images.githubusercontent.com/56601352/192789054-08286d11-3204-4233-afd8-cfc5209724a1.png)

WIth `<agua> a` it works fine:
![image](https://user-images.githubusercontent.com/56601352/192789103-640aa761-d8a9-46da-970a-cee70fd58fe4.png)

**Comment by xhyrom** [comment]
Same for `<<aqua>click:run_command:abc<aqua>>Click me for free cookies`

**Comment by xhyrom** [comment]
thanks!

**Comment by xHyroM** [comment]
thanks!
