### ISSUE TITLE
<lang:> does not work inside of gradients

### ISSUE THREAD

**Issue by AlessioGr** [KyoriPowered/adventure#827]
**Works:**
`You should get a <lang:block.minecraft.diamond_block>!`
<img width="354" alt="image" src="https://user-images.githubusercontent.com/70709113/198837432-d45eda4d-a3af-4fc5-a9bd-8df595508e3f.png">
**Doesn't work:**
`<gradient:#0fa111:#f1f1f1>You should get a <lang:block.minecraft.diamond_block>!</gradient>`
<img width="193" alt="image" src="https://user-images.githubusercontent.com/70709113/198837417-fd5cb7aa-e1f8-4dc9-9112-a6b80f414a88.png">

**Comment by rymiel** [comment]
Just to lower expectations, the linked fix wouldn't actually make the individual letters of the language tag have color, as that's physically impossible.
