### ISSUE TITLE
Question: parse text with both MiniMessage tags and legacy color codes

### ISSUE THREAD

**Issue by leonardo-dgs** [KyoriPowered/adventure#837]
I'm seeking a way to parse text that have both MiniMessage tags and legacy color codes.
I tried deserializing it with the legacy serializer, serializing it, and then deserializing it again with the MiniMessage parser, but the legacy serializer escapes the MiniMessage tags.

Anyone can say me how can I make work both MiniMessage tags and legacy color codes?

**Comment by zml2008** [comment]
This is not a feature we support now, or will ever support.
