### ISSUE TITLE
23w03a/1.19.4: Translation fallback field

### ISSUE THREAD

**Issue by ejm** [KyoriPowered/adventure#863]
In the newest Snapshot, Mojang introduced a change to `translate` components, a `fallback` field which contains a string to be used in the event that a translation key can't be found.

Full information can be found [here](https://www.minecraft.net/en-us/article/minecraft-snapshot-23w03a):
> Added an optional `fallback` field to `translate` text components.
> * The new field is a string that will be used in place of translation if it is missing
> * If `fallback` is missing, the old behavior (i.e. using the key itself as the translation) is preserved

Thanks!

**Comment by zml2008** [comment]
Fixed in #868
