### ISSUE TITLE
Provide a way to retain tags such as <rainbow> when serializing

### ISSUE THREAD

**Issue by Antonio32A** [KyoriPowered/adventure#872]
Attempting to serialize components which have rainbow or gradient tags results in the tag getting converted to a lot of individual color tags (see below). It would be useful to keep the rainbow tags when e.g. the user wants to convert from non-strict to strict format. 

Original text:
`<rainbow>test</rainbow>`
Expected output once deserialized and serialized back:
`<rainbow>test</rainbow>`
Actual output:
`<#f3801f>t</#f3801f><#4bff2c>e</#4bff2c><#0c80e0>s</#0c80e0><#b401d3>t</#b401d3>`

**Comment by zml2008** [comment]
See #842
