### ISSUE TITLE
Take TranslationComponent's fallback into account when serializing

### ISSUE THREAD

**Issue by dawon** [KyoriPowered/adventure#888]
When the server does serialize TranslationComponent (e.g. LegacySerializer) it should take a fallback translation of that Component into account, so when there is no translation available but there is a fallback, it should use that instead of displaying the translation key.

**Comment by zml2008** [comment]
In adventure itself, this will be fixed by #895 . Individual platforms will have to apply this fix as well if they use a custom serializer.
