### ISSUE TITLE
1.19.4 content(String) method ignored?

### ISSUE THREAD

**Issue by kangarko** [KyoriPowered/adventure#901]
In calling TextComponent#content(String) it appears to ignore the new content.

Context: I am using ProtocolLib and listening to ClientboundSystemChatPacket which has two fields, content and adventure$content. My goal is to edit these fields before the packet gets sent.

Before adventure, this was simple. Now I am trying to get the adventure$content field which works, but after setting its new content it appears not to work anymore.

The relevant code excerpt is here. Please note that the system.out prints out "ClientboundSystemChatPacket -> set to: " as if the new content is still empty even after it has been set.

<img width="1051" alt="Screenshot 2023-04-12 at 18 53 19" src="https://user-images.githubusercontent.com/1918426/231528328-1585d196-8f02-403e-9936-ad039c558d4e.png">

Using Paper build 510.

**Comment by Machine-Maker** [comment]
Components are immutable. Calling `adventureContent.content(message)` doesn't mutate `adventureContent`, it just returns a new component with that content.

**Comment by kangarko** [comment]
So how can I modify the content of the ClientboundSystemChatPacket?
