### ISSUE TITLE
Fallback parameter in TranslatableComponent doesn't insert params

### ISSUE THREAD

**Issue by Camotoy** [KyoriPowered/adventure#904]
Tested with Adventure 4.13.1.

`/tellraw @a {"translate":"test.missing","fallback":"My name is %s!","with":["Camotoy"]}`

Java 1.19.4: `My name is Camotoy!`

Adventure with TranslatableComponentRenderer and LegacyComponentSerializer: `My name is %s!`

**Comment by kashike** [comment]
Should be fixed with https://github.com/KyoriPowered/adventure/commit/be627303a65e7ac1fbebaa5f0f91f23150d8fc5e.
