### ISSUE TITLE
Expand named text color

### ISSUE THREAD

**Issue by masmc05** [KyoriPowered/adventure#910]
Now there are only color codes from java minecraft

Add new color codes that were added to bedrock edition <https://minecraft.fandom.com/wiki/Formatting_codes> 

Adding this and adding such support to MiniMessage should help server owners which have geyser, to easily add color codes for java minecraft (which support any color) and bedrock (which will only support these colors) 

Not necessarily in current class, but maybe in a new class

**Comment by MiniDigger** [comment]
is https://github.com/KyoriPowered/adventure/pull/906 of any use to you?

**Comment by zml2008** [comment]
I believe this is resolved by #906, though a potential bedrock module might make things even easier.
