### ISSUE TITLE
Some questions about translation

### ISSUE THREAD

**Issue by Birditch** [KyoriPowered/adventure#917]
I have some questions about translation.[The client language is switched repeatedly between Chinese and English (UK).]
When using Luckperms, I found the following phenomenon.
1. In my test server (using 192.168.0.xxx intranet) only LuckPerms in BungeeCord translated correctly, while Bukkit's LuckPerms used the default language.
![image](https://user-images.githubusercontent.com/73741466/236839617-2a5817b8-3e2a-4fe0-95ca-94b6600164e6.png)
2. In the framework of LuckPerms in the application of FloraCore plug-in, the default language is Chinese. But always show the English. Only the untranslated part will be displayed in Chinese.
![image](https://user-images.githubusercontent.com/73741466/236840113-891211e1-e8a4-4871-9010-0edccedd2d56.png)
![image](https://user-images.githubusercontent.com/73741466/236840223-07dd903f-0a27-4e6a-9c54-89a791e26f7c.png)
3. In my official server, however, I found that both /lpb in BungeeCord and /lp in Bukkit are accurately translated into the corresponding language of the client.
So I think that there must be some setting in my Bukkit that is preventing the correct translation, so how should I fix this problem?

**Comment by kezz** [comment]
This is a question you need to ask LuckPerms.
