### ISSUE TITLE
Play specific sounds are not allowed 😓

### ISSUE THREAD

**Issue by AstralBaby** [KyoriPowered/adventure#950]
Hi, I've been trying to play a specific sound this entire day until i realized it is not possible with this api.
`Sound.sound(Key.key("ambient.cave")` works fine.
But `Sound.sound(Key.key("ambient.cave.3")` does not work.
Thanks for your reply.

**Comment by kezz** [comment]
This is not an adventure issue, and likely an issue of whatever platform you are using. If you're using adventure-platform, please open the issue on that repo. Otherwise, if you are using a native implementation (paper/minestom/etc), please seek support with them instead.
