### ISSUE TITLE
`Formatter.date` resolver not working

### ISSUE THREAD

**Issue by zefir-git** [KyoriPowered/adventure#952]
The documentation says inserting an instance of `TemporalAccessor` is possible using `Formatter.date` resolver. However, when using `Date#toInstant()` which returns `Instant` (which is `TemporalAccessor`) the replacement is not done.

```java
Date date = new Date();
String message = "Date: <date:'yyyy-MM-dd HH:mm:ss'>";
sender.sendMessage(MiniMessage.miniMessage().deserialize(message, Formatter.date("date", Formatter.date("date", date.toInstant())));
// Message sent ↓
// Date: <date:'yyyy-MM-dd HH:mm:ss'>
```

No errors/warnings.

However, using the example from the docs (`LocalDateTime.now(ZoneId.systemDefault())`) works.

**Comment by Joo200** [comment]
Instants doesn't contain a timezone information. You can use `instant.atZone(ZoneId.systemDefault())` to get a TemporalAccessor with a timezone

**Comment by zefir-git** [comment]
@Joo200 I used `instant.atZone(ZoneOffset.UTC).toLocalDateTime()` and that worked. This might be good to mention in the docs as Instant is TemporalAccessor

**Comment by Pablete1234** [comment]
The requirement here isn't necessarily zone information, but support for time fields that you're using in your own format.
[Instant only supports limited fields](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/Instant.html#isSupported(java.time.temporal.TemporalField)), while you're requesting to use a format that uses years, months, hours, etc.
A [ZonedDateTime](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/ZonedDateTime.html#isSupported(java.time.temporal.TemporalField)), [OffsetDateTime](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/OffsetDateTime.html#isSupported(java.time.temporal.TemporalField)), or [LocalDateTime](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/LocalDateTime.html#isSupported(java.time.temporal.TemporalField)) should all support what you need here

In theory, even a [LocalDate](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/LocalDate.html#isSupported(java.time.temporal.TemporalField)) should be able to fill-in the formatting for `yyyy-MM-dd` just fine, but fail if you try to ask it for hour/min data, as that's something it cannot get.

I do believe it makes sene tho, that it throws some exception or log message when trying to use a temporal accesor that does not support all the fields you're requesting in the format
