### ISSUE TITLE
Make use of Java 17 sealed types

### ISSUE THREAD

**Issue by Sparky983** [KyoriPowered/adventure#955]
There are two main motivations for this change:

1. It enforces `@ApiStatus.NonExtendable` in the type system.
2. It allows code from future versions to effectively use [Pattern Matching for Switch](https://openjdk.org/jeps/441).

This change would need to be targeted for version 5.0.0 since it requires Java 17. It would also be very messy without the removal of `AbstractComponent`.

Additionally, I would like to lightly suggest that version 5.0.0 be written in Java 21 so that Adventure itself can take advantage of Pattern Matching for Switch.

**Comment by kashike** [comment]
#441
#459

**Comment by zml2008** [comment]
We are a text component/ingame UI library, not a "use Java features" library. This appears to be an issue that assumes we are the latter.

**Comment by Sparky983** [comment]
> We are a text component/ingame UI library, not a "use Java features" library. This appears to be an issue that assumes we are the latter.

Sorry, I don't understand. I'm simply suggesting that in in Adventure 5.0.0, that interfaces such as `Component` and `Tag` become `sealed`.
