### ISSUE TITLE
Tag resolvers don't apply in click actions 

### ISSUE THREAD

**Issue by NonSwag** [KyoriPowered/adventure#964]
I have a chat plugin which provides a tag for the message sent by the player (`<message>`).
I want to copy the message by clicking it, but it literally copies `<message>` instead of the actual message.

Here is the important part of the mini message:
`<click:copy_to_clipboard:'<message>'><message>`

I've tried to remove the apostrophes (`'`), but that's malformed syntax

Observed behavior:
![Screenshot from 2023-08-19 01-48-23](https://github.com/KyoriPowered/adventure/assets/54660361/c9a940cf-a09f-4d6b-bd19-bffddd1ea8eb)

Expected behavior:
![image](https://github.com/KyoriPowered/adventure/assets/54660361/759533bc-d546-4cbd-9a92-f0a264cfd1ed)

**Comment by kezz** [comment]
What is your tag? It will only work if it is a parsed tag as the argument for a click action is a literal string.
